LESSON = dict(
    id="phil-12", track="philosophy", minutes=3,
    title="The prisoner's dilemma",
    blurb="Two people who both act sensibly can both end up worse off. Here's the setup, the numbers, why it shows up in group projects, and the strategy that won.",
    takeaway="You learned why cooperation is hard and what makes it work anyway.",
    cards=[
        dict(kind="image", src="p01-two-doors", eyebrow="Two rooms",
             body="Two suspects are arrested and put in separate rooms. Each is offered the same deal. Stay silent, or talk. Neither knows what the other will do. This is the prisoner's dilemma.",
             paint="A plain police-station corridor, two closed doors side by side with small frosted windows, a uniformed officer walking away down the corridor carrying two folders, cool fluorescent light. Exactly one person. No words on the doors, folders, or signs. The card says: two suspects in separate rooms, each offered the same deal."),
        dict(kind="image", src="fig-02-matrix", eyebrow="The deal",
             body="If both stay silent, one year each. If one talks and the other stays silent, the talker walks free and the silent one gets ten. If both talk, five years each."),
        dict(kind="image", src="fig-03-logic", eyebrow="Why both talk",
             body="Look from one side. If the other stays silent, talking gets you zero instead of one. If the other talks, talking gets you five instead of ten. Talking wins either way. So both talk."),
        dict(kind="image", src="fig-04-trap", eyebrow="The trap",
             body="That is the dilemma. Each choice was sensible. Together they made the worst shared outcome. Both silent was better for both. Neither could risk it. This is what a dilemma means."),
        dict(kind="image", src="p05-group-project", eyebrow="It's your group project",
             body="Four people, one grade. If everyone works, it is great. If you slack and they work, you get the grade for free. If everyone slacks, everyone fails. Same game, no prison.",
             paint="A library study table with four college students: three leaning in over laptops and papers, working, and one leaning back in their chair scrolling a phone with a bored face. Warm library lamps, shelves behind with plain-coloured book spines. Exactly four people. No words on screens, papers, or spines. The card says: four people, one grade, and one of them is slacking."),
        dict(kind="image", src="fig-06-repeat", eyebrow="Play it more than once",
             body="Real life repeats. The group meets again next week. Now slacking has a cost, because they remember. Repeating the game is what makes cooperation possible."),
        dict(kind="image", src="fig-07-tit-for-tat", eyebrow="The strategy that won",
             body="In 1980 a scientist ran a tournament of strategies for the repeated game. The winner was the simplest. Cooperate first. Then copy what the other did last time. It is called tit for tat."),
        dict(kind="image", src="fig-08-four-rules", eyebrow="Four rules",
             body="Tit for tat won for four reasons. Be nice: never cheat first. Retaliate: answer cheating straight away. Forgive: go back to cooperating as soon as they do. Be clear: so they can predict you."),
        dict(kind="image", src="p09-handshake", eyebrow="In the room",
             body="So in the group project, work first. If someone slacks, say so the same week, plainly. When they show up again, drop it. Be someone whose next move is easy to guess.",
             paint="The same library table a week later: all four college students working together now, one of them, the former slacker, sliding a page across the table with a sheepish grin, another giving a small nod of thanks. Warm light. Exactly four people. No words on anything. The card says: work first, say so plainly if someone slacks, and drop it when they show up again."),
        dict(kind="key", body="Sensible choices can add up to the worst outcome. Repetition fixes it: nice, firm, forgiving, clear."),
        dict(kind="check",
             question="In the dilemma, why do both suspects end up talking?",
             choices=["Talking is better for each one, whatever the other does",
                      "Each thinks the other one is more likely to talk first",
                      "The police offer a better deal to whoever talks first"],
             answer=0,
             why="Check each row. Whatever the other person does, talking gives you a shorter sentence. Both follow that logic, and both land on five years instead of one."),
    ])
