LESSON = dict(
    id="work-9", track="work", minutes=3,
    title="A resume gets seven seconds",
    blurb="A recruiter's first look at your resume lasts about seven seconds. Here's what they see in that time, the bullet shape that survives it, and what to cut.",
    takeaway="You learned to write a resume for a seven-second read.",
    cards=[
        dict(kind="image", src="p01-stack", eyebrow="The pile",
             body="A recruiter opens two hundred resumes for one job. Yours gets about seven seconds on the first pass. Not seven minutes. Seven seconds, then keep or skip.",
             paint="A recruiter in their thirties at a desk, one hand on a mouse, eyes on a monitor that shows only a tall list of identical grey document thumbnails, a tall stack of printed pages at their elbow, a coffee, morning office light. Exactly one person. No readable words on the screen or pages. The card says: two hundred resumes for one job, and yours gets about seven seconds."),
        dict(kind="image", src="fig-02-what-it-is", eyebrow="What it is",
             body="A resume is not your life story. It is a one-page argument that you can do this job. Every line either helps that argument or takes space from a line that would."),
        dict(kind="image", src="fig-03-eyes", eyebrow="Where the eyes go",
             body="Eye-tracking studies show the first look is an F shape. The top third, the left edge, the bold words. Your name, your latest job, and the first bullet under it carry almost everything."),
        dict(kind="image", src="fig-04-bullet", eyebrow="The bullet shape",
             body="Verb, what, number. 'Ran the club's Instagram' says nothing. 'Grew the club's Instagram from 200 to 1,400 followers in a year' says you can do a thing, and proves it."),
        dict(kind="image", src="p05-numbers", eyebrow="Find the numbers",
             body="Every job has numbers, even the ones that feel small. How many customers a shift. How many hours a week. How much money handled. Go back through each job and dig them out.",
             paint="A college student working a busy cafe counter, handing a cup to one customer while a short line of three more waits, a tip jar and a card reader with a blank screen on the counter, warm afternoon light. Exactly five people. No menu boards, no logos, no words. The card says: every job has numbers, even the ones that feel small."),
        dict(kind="image", src="fig-06-cut", eyebrow="What to cut",
             body="Cut the objective statement. Cut 'references available'. Cut high school once you are in college. Cut every adjective about yourself. 'Hard-working' is a claim. A number is proof."),
        dict(kind="image", src="fig-07-keywords", eyebrow="Match the posting",
             body="Many companies scan resumes by software before a person sees them. Use the posting's own words for skills. If it says 'data analysis', you say 'data analysis', not 'crunching numbers'."),
        dict(kind="image", src="p08-test", eyebrow="The seven-second test",
             body="Hand it to a friend. Count to seven. Take it back. Ask what job you are applying for and what your best thing is. If they cannot say, the top third is not doing its job.",
             paint="Two college students on a dorm-room floor, one holding a single printed page at arm's length and squinting at it with a grin, the other counting on their fingers with a mock-serious face. Cosy lamp light, a bed and a mini fridge behind. Exactly two people. The page shows only grey squiggled lines, no words. The card says: hand it to a friend, count to seven, take it back."),
        dict(kind="image", src="p09-one-page", eyebrow="One page, PDF",
             body="One page. Plain font. Saved as a PDF with your name in the file name. That is a resume a stranger can read in seven seconds, and a machine can read at all.",
             paint="Close view of a clean desk from above: a college student's hands holding one crisp printed page with a tidy layout of grey lines and a few bold grey bars at the top, a closed laptop, a pen, morning light. One person's hands only, no face. No readable words on the page. The card says: one page, plain font, saved as a PDF with your name in the file name."),
        dict(kind="key", body="Seven seconds, top third, verb-what-number. Cut everything that isn't proof."),
        dict(kind="check",
             question="Which bullet survives a seven-second read?",
             choices=["'Cut checkout wait times 30% by adding a second register at peak'",
                      "'Responsible for customer service and store operations at peak'",
                      "'Hard-working team player with strong communication and drive'"],
             answer=0,
             why="It starts with a verb, says what changed, and gives a number. The other two are claims anyone could make, so they prove nothing in the time you have."),
    ])
