LESSON = dict(
    id='work-9', track='work', minutes=3,
    title='A resume gets seven seconds',
    blurb="A recruiter's first look at your resume lasts about seven seconds. You'll see what they read in that time, the bullet shape that survives it, and the four things to cut tonight.",
    takeaway='Write the resume for a seven-second read: top third, verb, what, number.',
    cards=[
        dict(kind='image', src='p01-stack', eyebrow='The pile',
             body='A recruiter opens two hundred resumes for one job, and yours gets about seven seconds on the first pass. Not seven minutes. Seven seconds, then keep or skip, and the top third decides which.',
             paint='A recruiter in their thirties at a desk, one hand on a mouse, eyes on a monitor that shows only a tall list of identical grey document thumbnails, a tall stack of printed pages at their elbow, a coffee, morning office light. Exactly one person. No readable words on the screen or pages. The card says: two hundred resumes for one job, and yours gets about seven seconds.'),
        dict(kind='image', src='fig-02-what-it-is', eyebrow='What it is',
             body="A resume isn't your life story. It's a one-page argument that you can do this job, and every line either helps that argument or takes space from a line that would. That's the only editing rule you need."),
        dict(kind='image', src='fig-03-eyes', eyebrow='Where the eyes go',
             body='Eye-tracking research by Ladders in 2018 clocked the first look at 7.4 seconds, moving in an F shape: the top third, the left edge, the bold words. Your name, your latest job, and its first bullet carry almost everything.'),
        dict(kind='image', src='fig-04-bullet', eyebrow='The bullet shape',
             body="Verb, what, number. 'Ran the club's Instagram' says nothing. 'Grew the club's Instagram from 200 to 1,400 followers in a year' says you can do a thing and proves it, in the same amount of space."),
        dict(kind='image', src='p05-numbers', eyebrow='Find the numbers',
             body='Every job has numbers, even the ones that feel small. How many customers a shift, how many hours a week, how much money you handled. Go back through each job and dig them out, because nobody else will.',
             paint='A college student working a busy cafe counter, handing a cup to one customer while a short line of three more waits, a tip jar and a card reader with a blank screen on the counter, warm afternoon light. Exactly five people. No menu boards, no logos, no words. The card says: every job has numbers, even the ones that feel small.'),
        dict(kind='image', src='fig-06-cut', eyebrow='What to cut',
             body="Cut the objective statement, 'references available', and high school once you're in college. Cut every adjective about yourself. 'Hard-working' is a claim anyone can make, and a number is proof nobody can argue with."),
        dict(kind='image', src='fig-07-keywords', eyebrow='Match the posting',
             body="Many companies run resumes through software before a person sees them. Use the posting's own words for skills: if it says 'data analysis', you say 'data analysis', not 'crunching numbers', or the software never finds you."),
        dict(kind='image', src='p08-test', eyebrow='The seven-second test',
             body="Hand it to a friend, count to seven, take it back. Ask what job you're applying for and what your best thing is. If they can't say, the top third isn't doing its job, and page two won't save it.",
             paint="Two college students on a dorm-room floor, one holding a single printed page at arm's length and squinting at it with a grin, the other counting on their fingers with a mock-serious face. Cosy lamp light, a bed and a mini fridge behind. Exactly two people. The page shows only grey squiggled lines, no words. The card says: hand it to a friend, count to seven, take it back."),
        dict(kind='image', src='p09-one-page', eyebrow='One page, PDF',
             body="One page, plain font, saved as a PDF with your name in the file name. That's a resume a stranger can read in seven seconds and a machine can read at all. Two pages is for people ten years in.",
             paint="Close view of a clean desk from above: a college student's hands holding one crisp printed page with a tidy layout of grey lines and a few bold grey bars at the top, a closed laptop, a pen, morning light. One person's hands only, no face. No readable words on the page. The card says: one page, plain font, saved as a PDF with your name in the file name."),
        dict(kind='key', body="Seven seconds, top third, verb-what-number. Cut everything that isn't proof."),
        dict(kind='check',
             question='Which bullet survives a seven-second read?',
             choices=["'Cut checkout wait times 30% by adding a second register at peak'", "'Responsible for customer service and store operations at peak'", "'Hard-working team player with strong communication and drive'"],
             answer=0,
             why='It starts with a verb, says what changed, and gives a number, while the other two are claims anyone could make.'),
    ])
