LESSON = dict(
    id='work-7', track='work', minutes=3,
    title='How to quit without burning the bridge',
    blurb="Leaving a job well takes about ten days and four moves. You'll see who hears first, what the three-line email is for, what a counteroffer usually fixes, and what to say on the way out.",
    takeaway='Leave so the people you leave would hire you again.',
    cards=[
        dict(kind='image', src='p01-decision', eyebrow="You're leaving",
             body="You've signed a new offer and now there's the old job. Most people get this part wrong by being rushed, not rude. Ten days of care here pays off for years, because these are the people your next employer calls.",
             paint='A college-age person at home in the evening, sitting at a small desk with a printed letter in one hand, looking out of the window with a calm, decided expression, a mug beside them, warm lamplight. Exactly one person. The letter shows only grey squiggled lines, no words. The card says: you have a new offer signed, now the old job, and this part rewards care.'),
        dict(kind='image', src='fig-02-notice', eyebrow='What notice is',
             body="Notice is the warning you give before you go. Two weeks is the US custom, not a law, and most states let either side end a job on the spot. Give it anyway. It's the cheap price of a good reference."),
        dict(kind='image', src='fig-03-order', eyebrow='Who hears first',
             body='Your manager hears first, live, before anyone else. Then a short email confirming the date, then your team once your manager says so. Never Slack first and never a coworker first, however close you are.'),
        dict(kind='image', src='p04-conversation', eyebrow='The conversation',
             body="Keep it short and kind: 'I've accepted another role. My last day is the 24th. I want to make the handover easy.' No list of grievances. You aren't asking permission, you're informing them, and they'll respect that more.",
             paint='A quiet one-to-one in a small office: a college-age employee sitting upright and composed, speaking plainly, and a manager across the desk listening with a surprised but respectful expression, hands folded. Soft daylight. Exactly two people. No screens with words, no papers with letters. The card says: keep it short and kind, you are informing, not asking.'),
        dict(kind='image', src='fig-05-email', eyebrow='The email',
             body="Three lines: that you're resigning, your last day, and thanks. It goes in your file and gets read again when someone calls about you in two years. Write it for that reader, not for today's mood."),
        dict(kind='image', src='fig-06-counter', eyebrow='The counteroffer',
             body='They might offer more money to stay. Ask yourself why it took quitting to get it. A counteroffer fixes the pay, so ask what else changes, and if the answer is nothing, the answer is still no.'),
        dict(kind='image', src='p07-handover', eyebrow='The handover doc',
             body="Spend your last week writing the document you wish you'd been given: where things live, what's due, who to ask. Hand it over in a real meeting. It's the thing they'll remember about you a year from now.",
             paint='A college-age employee and a younger coworker side by side at one desk, the employee walking the coworker through a printed stapled document, pointing at a line, the coworker nodding and taking notes. Bright office afternoon. Exactly two people. The document shows only grey squiggled lines and coloured boxes, no words. The card says: write the handover you wish you had been given, then hand it over in a real meeting.'),
        dict(kind='image', src='fig-08-exit', eyebrow='The exit interview',
             body="HR might ask why you're leaving. Be honest about the job and quiet about the people. Nothing you say here changes your old team, but it can follow you, so keep it short, true, and warm."),
        dict(kind='image', src='p09-last-day', eyebrow='Last day',
             body="Say goodbye in person to the people who taught you something. Send your personal email to the three you want to keep. The bridge you leave standing is your next reference, and you won't know which one until you need it.",
             paint='A last-day goodbye in an office kitchen: a college-age employee holding a small cardboard box of desk things, shaking hands warmly with an older colleague while two others smile nearby, one holding a coffee. Exactly four people. No words on the box, mugs, or walls. The card says: say goodbye in person to the people who taught you something.'),
        dict(kind='key', body='Manager first, in person. Two weeks. A handover doc. Warm on the way out.'),
        dict(kind='check',
             question="You've accepted a new job. Who hears about it first?",
             choices=['Your manager, live, before anyone else', "Your closest coworker, so it isn't a shock", 'HR, so the paperwork starts right away'],
             answer=0,
             why="A manager who hears it secondhand feels blindsided, and that's the person your next employer will call."),
    ])
