LESSON = dict(
    id="work-7", track="work", minutes=3,
    title="How to quit without burning the bridge",
    blurb="Leaving a job well takes ten days and four moves. Here's who hears first, what to write, what a counteroffer usually means, and what to say on your way out.",
    takeaway="You learned to leave so the people you leave would hire you again.",
    cards=[
        dict(kind="image", src="p01-decision", eyebrow="You're leaving",
             body="You have a new offer, signed. Now the old job. Most people get this part wrong, not by being rude but by being rushed. Ten days of care here pays off for years.",
             paint="A college-age person at home in the evening, sitting at a small desk with a printed letter in one hand, looking out of the window with a calm, decided expression, a mug beside them, warm lamplight. Exactly one person. The letter shows only grey squiggled lines, no words. The card says: you have a new offer signed, now the old job, and this part rewards care."),
        dict(kind="image", src="fig-02-notice", eyebrow="What notice is",
             body="Notice is the warning you give before you go. Two weeks is the custom in the US, not a law. Give it anyway. It is the price of a good reference, and it is cheap."),
        dict(kind="image", src="fig-03-order", eyebrow="Who hears first",
             body="Your manager hears first, live, before anyone else. Then a short email confirming the date. Then your team, once your manager says so. Never Slack first. Never a coworker first."),
        dict(kind="image", src="p04-conversation", eyebrow="The conversation",
             body="Keep it short and kind. 'I've accepted another role. My last day is the 24th. I want to make the handover easy.' No list of grievances. You are not asking. You are informing.",
             paint="A quiet one-to-one in a small office: a college-age employee sitting upright and composed, speaking plainly, and a manager across the desk listening with a surprised but respectful expression, hands folded. Soft daylight. Exactly two people. No screens with words, no papers with letters. The card says: keep it short and kind, you are informing, not asking."),
        dict(kind="image", src="fig-05-email", eyebrow="The email",
             body="Three lines. That you are resigning, your last day, and thanks. It goes in your file and gets read again when someone calls for a reference. Write it for that reader."),
        dict(kind="image", src="fig-06-counter", eyebrow="The counteroffer",
             body="They may offer more money to stay. Ask yourself why it took quitting to get it. A counteroffer fixes the pay. Ask what else changes. If the answer is nothing, the answer is no."),
        dict(kind="image", src="p07-handover", eyebrow="The handover doc",
             body="Spend your last week writing the document you wish you had been given. Where things live, what is due, who to ask. Hand it over in a real meeting. This is what they remember.",
             paint="A college-age employee and a younger coworker side by side at one desk, the employee walking the coworker through a printed stapled document, pointing at a line, the coworker nodding and taking notes. Bright office afternoon. Exactly two people. The document shows only grey squiggled lines and coloured boxes, no words. The card says: write the handover you wish you had been given, then hand it over in a real meeting."),
        dict(kind="image", src="fig-08-exit", eyebrow="The exit interview",
             body="HR may ask why you are leaving. Be honest about the job, quiet about the people. Nothing said here changes your old team, but it can follow you. Short, true, and warm."),
        dict(kind="image", src="p09-last-day", eyebrow="Last day",
             body="Say goodbye in person to the people who taught you something. Send your personal email to the three you want to keep. The bridge you leave standing is your next reference.",
             paint="A last-day goodbye in an office kitchen: a college-age employee holding a small cardboard box of desk things, shaking hands warmly with an older colleague while two others smile nearby, one holding a coffee. Exactly four people. No words on the box, mugs, or walls. The card says: say goodbye in person to the people who taught you something."),
        dict(kind="key", body="Manager first, in person. Two weeks. A handover doc. Warm on the way out."),
        dict(kind="check",
             question="You've accepted a new job. Who hears about it first?",
             choices=["Your manager, live, before anyone else",
                      "Your closest coworker, so it isn't a shock",
                      "HR, so the paperwork starts right away"],
             answer=0,
             why="A manager who hears it from someone else feels blindsided, and that is the person your next employer will call. Tell them first, then confirm in writing."),
    ])
