"""Hand-written Ladder puzzles (Crossclimb-type).

Seven five-letter words in ladder order, each one letter off the next, and a
clue for each. The middle five are dealt to the player scrambled; the first
and last are the locked top and bottom rungs, revealed once the middle is in
order. Every word must be in words.json (the common list); gen.py checks that,
that neighbours differ by exactly one letter, and that the middle five have only
one valid order (up to reversal).

To author more, run `python3 design/games/gen.py candidates` and pick chains
whose words all take a short, unambiguous clue.
"""

LADDERS = [
    (["CREEP", "CREEK", "CHEEK", "CHEER", "SHEER", "SHEEP", "SHEET"],
     ["Move slowly and quietly", "Small stream", "Where a blush shows", "Crowd's roar of support",
      "See-through, as curtains", "Wool on legs", "Bed linen, or a page of paper"]),
    (["FLOUR", "FLOOR", "FLOOD", "BLOOD", "BLOOM", "BROOM", "BROOK"],
     ["Baker's white powder", "What you stand on indoors", "River over its banks", "It's thicker than water",
      "A flower opening", "Witch's ride, or a sweeper", "Babbling stream"]),
    (["SNEAK", "SPEAK", "SPEAR", "SWEAR", "SWEAT", "SWEPT", "SWEET"],
     ["Move like a ninja", "Use your voice", "Pointed throwing weapon", "Curse, or take an oath",
      "Gym-session result", "Cleaned with a broom", "Like candy"]),
    (["SLIME", "SLICE", "SPICE", "SPITE", "SPINE", "SHINE", "SHINY"],
     ["Gooey green goo", "Piece of pizza", "Cinnamon or cumin", "Malice; 'in ___ of'",
      "Backbone", "Glow or polish", "Glossy and bright"]),
    (["FLICK", "CLICK", "CLOCK", "FLOCK", "BLOCK", "BLACK", "BLANK"],
     ["Quick finger snap, or a movie", "Mouse-button sound", "Wall timekeeper", "Group of birds or sheep",
      "City street unit, or a stop", "Darkest color", "Empty, like this space"]),
    (["LEASE", "LEAST", "BEAST", "BLAST", "BOAST", "COAST", "ROAST"],
     ["Apartment rental contract", "Smallest amount", "Wild animal", "Explosion; a great time",
      "Brag", "Where land meets sea", "Cook in the oven, or mock"]),
    (["BLAND", "BLEND", "BLIND", "BLINK", "BRINK", "BRISK", "BRICK"],
     ["Lacking flavor", "Mix in a smoothie", "Window shade", "Quick eye shut",
      "Edge of a cliff", "Quick and energetic", "Wall building block"]),
    (["SKIRT", "SHIRT", "SHORT", "SHORE", "SCORE", "SCARE", "SPARE"],
     ["Garment that hangs from the waist", "Top with sleeves", "Not tall", "Beach edge",
      "Game total", "Frighten", "Extra tire, or a bowling result"]),
    (["TRAIL", "TRAIT", "TRAIN", "GRAIN", "DRAIN", "DRAWN", "DROWN"],
     ["Hiking path", "Personality feature", "Track vehicle", "Wheat or rice; wood pattern",
      "Sink's exit", "Sketched", "Sink under water, fatally"]),
    (["GRASP", "GRASS", "GLASS", "CLASS", "CLASH", "FLASH", "FLUSH"],
     ["Grip, or understand", "Lawn greenery", "Window material", "Lecture group",
      "Colors that fight", "Camera's burst of light", "Toilet handle action"]),
    (["CEASE", "CHASE", "CHOSE", "WHOSE", "THOSE", "THESE", "THERE"],
     ["Stop", "Run after", "Picked (past tense)", "Belonging to whom",
      "Not these", "Not those", "Not here"]),
    (["PLANE", "PLANK", "BLANK", "BLINK", "BRINK", "DRINK", "DRANK"],
     ["Airport departure", "Core exercise, or a pirate's walk", "Fill-in-the-___", "Eye flicker",
      "Verge", "Sip", "Sipped (past tense)"]),
    (["SMOKE", "SPOKE", "SPIKE", "SPITE", "SUITE", "QUITE", "QUOTE"],
     ["Fire's gray plume", "Bike wheel rod", "Volleyball slam", "Petty malice",
      "Fancy hotel room", "Fairly; rather", "Words in quotation marks"]),
    (["STONE", "STORE", "STARE", "STATE", "SLATE", "PLATE", "PLANE"],
     ["Rock", "Shop", "Long hard look", "Texas or Ohio",
      "Chalkboard rock", "Dinner dish", "Jet"]),
    (["GIANT", "GRANT", "GRAND", "BRAND", "BLAND", "BLEND", "BLIND"],
     ["Huge; Jack's beanstalk foe", "Scholarship money", "A thousand dollars, in slang", "Nike or Apple",
      "Flavorless", "Smoothie action", "Unable to see"]),
    (["PUNCH", "LUNCH", "BUNCH", "BENCH", "BEACH", "PEACH", "TEACH"],
     ["Boxer's hit, or a party bowl", "Midday meal", "Bananas come in one", "Park seat",
      "Sandy shore", "Fuzzy fruit", "Instruct"]),
    (["GRAPE", "GRAVE", "GRADE", "TRADE", "TRACE", "TRACK", "CRACK"],
     ["Wine fruit", "Serious; burial site", "A, B or C", "Swap",
      "Copy through thin paper", "Race path; a song", "Split in a phone screen"]),
    (["CLASH", "CRASH", "CRUSH", "CRUST", "CREST", "CHEST", "CHEAT"],
     ["Conflict", "Car accident", "Secret romantic interest", "Pizza edge",
      "Top of a wave", "Treasure box", "Copy off a neighbor's test"]),
    (["CIDER", "RIDER", "RIVER", "DIVER", "LIVER", "LEVER", "LEVEL"],
     ["Fall apple drink", "Horse's passenger", "Mississippi, e.g.", "Scuba enthusiast",
      "Organ that filters blood", "Bar that pries", "Flat; a video game stage"]),
    (["SHAVE", "SHADE", "SHARE", "SHORE", "STORE", "STORM", "STORY"],
     ["Razor job", "Tree's cool spot; a subtle insult", "Split with friends", "Coastline",
      "Retail shop", "Thunder and lightning", "Tale"]),
    (["THINK", "THICK", "TRICK", "BRICK", "BRINK", "BRING", "BEING"],
     ["Ponder", "Not thin", "Magician's act", "Clay building block",
      "Edge", "Carry along", "A living creature; existence"]),
    (["SHARK", "SPARK", "SPARE", "SCARE", "SHARE", "SHORE", "SCORE"],
     ["Ocean predator with fins", "Tiny flash of fire", "Extra", "Frighten",
      "Give part of", "Beach", "Points total"]),
    (["MATCH", "CATCH", "WATCH", "WITCH", "PITCH", "PINCH", "PUNCH"],
     ["Fire starter; a tennis game", "Grab a ball", "Wrist timepiece", "Broomstick flyer",
      "Baseball throw; a sales talk", "Small squeeze; a bit of salt", "Fist hit"]),
    (["WHALE", "WHOLE", "WHOSE", "CHOSE", "CHASE", "CEASE", "LEASE"],
     ["Largest ocean mammal", "Entire", "Belonging to which person", "Selected",
      "Pursue", "Stop", "Rental agreement"]),
    (["STYLE", "STOLE", "STORE", "SHORE", "SCORE", "SCARE", "SCARF"],
     ["Fashion sense", "Took (past tense)", "Shop", "Coast",
      "Points", "Spook", "Winter neck wrap"]),
    (["STARE", "STAKE", "STATE", "SKATE", "SLATE", "PLATE", "PLACE"],
     ["Gaze", "Vampire slayer's tool; a bet", "One of fifty", "Glide on ice",
      "Gray roofing rock", "Dish", "Location"]),
    (["WEAVE", "LEAVE", "LEASE", "LEAST", "BEAST", "BOAST", "TOAST"],
     ["Make cloth on a loom", "Depart", "Rent contract", "Minimum",
      "Monster", "Brag", "Browned bread; a raised glass"]),
    (["BROKE", "BRAKE", "BRAVE", "GRAVE", "GROVE", "GLOVE", "GLOBE"],
     ["Out of money", "Car's stopper", "Courageous", "Cemetery plot",
      "Small group of trees", "Hand warmer", "Spinning world model"]),
    (["STAGE", "STATE", "STALE", "SCALE", "SCARE", "SCORE", "SCOPE"],
     ["Where actors perform", "Nation subdivision", "Old bread's state", "Bathroom weigher",
      "Frighten", "Final tally", "Range; a telescope part"]),
    (["DRONE", "PRONE", "PROVE", "GROVE", "GRAVE", "GRAPE", "GRAPH"],
     ["Buzzing quadcopter", "Lying face-down; likely to", "Show to be true", "Orange trees, together",
      "Solemn", "Raisin, before drying", "Chart with axes"]),
    (["MARCH", "MATCH", "PATCH", "PITCH", "PINCH", "PUNCH", "LUNCH"],
     ["Third month; a soldiers' walk", "Tinder success", "Software fix; jeans repair", "Startup's sales talk",
      "Crab's grab", "Fruit-bowl party drink", "Noon meal"]),
    (["GRACE", "TRACE", "TRACK", "TRUCK", "TRICK", "THICK", "THINK"],
     ["Elegance; a pre-meal prayer", "Faint sign; outline on paper", "Running oval", "Pickup, e.g.",
      "Card magician's move", "Dense", "Use your brain"]),
    (["SLEEK", "SLEEP", "STEEP", "STEER", "STEEL", "STEAL", "STEAK"],
     ["Smooth and glossy", "What all-nighters skip", "Sharply sloped", "Aim a car",
      "Skyscraper metal", "Take without asking", "Grill-night main"]),
    (["PLANT", "PLANE", "PLACE", "PEACE", "PEACH", "TEACH", "REACH"],
     ["Green thing in a pot", "Boeing product", "Spot", "Opposite of war",
      "Georgia's fruit", "Run a classroom", "Stretch to grab"]),
    (["FRESH", "FLESH", "FLASH", "CLASH", "CLASS", "GLASS", "GRASS"],
     ["Just picked", "Skin and muscle", "Lightning's burst", "Fight",
      "Section of a course", "Drinking vessel", "Mowed greenery"]),
    (["STEEP", "STEEL", "STEER", "SHEER", "CHEER", "CHEEK", "CHECK"],
     ["Like a ski slope", "Iron alloy", "Guide the wheel", "Very thin, as tights",
      "Pep-rally shout", "Face's side", "Tick mark; restaurant bill"]),
    (["SLIME", "SLIDE", "SLICE", "SPICE", "SPIKE", "SPOKE", "SMOKE"],
     ["Kids' gooey toy", "Playground chute", "Pizza portion", "Pepper or paprika",
      "Sharp point; a sudden jump", "Talked (past tense)", "What there's fire behind"]),
    (["LEASH", "LEASE", "CEASE", "CHASE", "CHOSE", "WHOSE", "WHOLE"],
     ["Dog walker's strap", "Landlord's contract", "Halt", "Run after",
      "Picked", "Of which person", "Complete"]),
    (["CLOCK", "FLOCK", "BLOCK", "BLACK", "BLANK", "BLAND", "BLEND"],
     ["Alarm ___", "Birds in formation", "Lego piece; a Tetris unit", "Color of a tuxedo",
      "Empty", "Needs salt", "Mix"]),
    (["SWEET", "SWEPT", "SWEAT", "SWEAR", "SPEAR", "SPEAK", "STEAK"],
     ["Sugary", "Brushed off the floor", "Perspire", "Use a four-letter word",
      "Tip-first hunting weapon", "Talk", "Ribeye or sirloin"]),
]
