"""Sort puzzles (a Connections-type game), hand-written.

Each puzzle is (hard, [(group name, [four words]), ...]) with the groups in the
order easiest to hardest. Sixteen words, no repeats. A word that fits two groups
on purpose is the trap: the answer is the one the other three words leave open.
`hard` is 1-5, the author's call, and is what rate.py ranks the pool by.

gen.py checks every puzzle: four groups of four, sixteen different words, and
deals each one a shuffled board order.
"""

SORTS = [
 (1, [("Coffee orders", ["LATTE", "MOCHA", "ESPRESSO", "CORTADO"]),
      ("In a backpack", ["LAPTOP", "CHARGER", "NOTEBOOK", "PENCIL"]),
      ("Ways to say yes", ["SURE", "YEP", "TOTALLY", "ABSOLUTELY"]),
      ("___ hall", ["DINING", "STUDY", "LECTURE", "TOWN"])]),
 (2, [("Dorm essentials", ["FAN", "LAMP", "MIRROR", "FRIDGE"]),
      ("Group project roles", ["LEADER", "EDITOR", "RESEARCHER", "PRESENTER"]),
      ("___ card", ["CREDIT", "REPORT", "GIFT", "INDEX"]),
      ("Anagrams of each other", ["LISTEN", "SILENT", "ENLIST", "TINSEL"])]),
 (2, [("Chess pieces", ["KING", "QUEEN", "ROOK", "BISHOP"]),
      ("Social apps", ["SNAP", "TIKTOK", "DISCORD", "BEREAL"]),
      ("Things you cram", ["FACTS", "FORMULAS", "DATES", "VOCAB"]),
      ("Slang for great", ["FIRE", "SLAPS", "GOATED", "ELITE"])]),
 (3, [("Exam types", ["MIDTERM", "FINAL", "QUIZ", "PRACTICAL"]),
      ("Candy bars", ["SNICKERS", "TWIX", "KITKAT", "MILKYWAY"]),
      ("On a bagel", ["LOX", "BUTTER", "JAM", "SCHMEAR"]),
      ("Planets", ["MARS", "VENUS", "SATURN", "MERCURY"])]),
 (2, [("Library noises", ["SHUSH", "COUGH", "WHISPER", "RUSTLE"]),
      ("Things with keys", ["PIANO", "LAPTOP", "MAP", "LOCK"]),
      ("Poker moves", ["FOLD", "RAISE", "CALL", "CHECK"]),
      ("___ break", ["SPRING", "COFFEE", "LUNCH", "BRAIN"])]),
 (3, [("Cereals", ["CHEERIOS", "CHEX", "KIX", "TRIX"]),
      ("Airlines", ["UNITED", "SPIRIT", "FRONTIER", "ALASKA"]),
      ("Greek letters", ["BETA", "DELTA", "KAPPA", "SIGMA"]),
      ("Hot ___", ["TAKE", "DOG", "SAUCE", "SPOT"])]),
 (2, [("Gems", ["RUBY", "OPAL", "JADE", "AMBER"]),
      ("Programming languages", ["PYTHON", "SWIFT", "RUST", "JAVA"]),
      ("Note apps", ["NOTION", "OBSIDIAN", "EVERNOTE", "GOODNOTES"]),
      ("Dorm room sounds", ["ALARM", "MICROWAVE", "VACUUM", "HAIRDRYER"])]),
 (3, [("Textbook parts", ["INDEX", "GLOSSARY", "PREFACE", "CHAPTER"]),
      ("Things you pull", ["MUSCLE", "PRANK", "STRINGS", "WEIGHT"]),
      ("Fingers", ["THUMB", "PINKY", "RING", "MIDDLE"]),
      ("___ school", ["GRAD", "LAW", "MED", "OLD"])]),
 (2, [("Study spots", ["LIBRARY", "CAFE", "LOUNGE", "QUAD"]),
      ("Card games", ["UNO", "SPADES", "HEARTS", "WAR"]),
      ("Yoga poses", ["COBRA", "TREE", "WARRIOR", "CHILD"]),
      ("Pizza chains", ["DOMINOS", "SBARRO", "BLAZE", "MOD"])]),
 (3, [("Halloween", ["PUMPKIN", "WITCH", "CANDY", "COSTUME"]),
      ("Sports gear", ["BAT", "GLOVE", "PUCK", "RACKET"]),
      ("Meal plan words", ["SWIPE", "DINING", "BUFFET", "TRAY"]),
      ("Dating app verbs", ["MATCH", "LIKE", "GHOST", "UNMATCH"])]),
 (2, [("Show genres", ["DRAMA", "COMEDY", "THRILLER", "DOCUMENTARY"]),
      ("Fish", ["TROUT", "SALMON", "TUNA", "COD"]),
      ("Email verbs", ["FORWARD", "REPLY", "DRAFT", "ARCHIVE"]),
      ("Band instruments", ["DRUMS", "BASS", "KEYS", "SAX"])]),
 (3, [("Transit", ["TRAM", "BUS", "FERRY", "METRO"]),
      ("Things you set", ["ALARM", "TABLE", "GOALS", "RECORD"]),
      ("Video game heroes", ["MARIO", "LINK", "KIRBY", "SAMUS"]),
      ("Fast food", ["SUBWAY", "PANERA", "WENDYS", "SONIC"])]),
 (2, [("Highlighter colors", ["YELLOW", "PINK", "GREEN", "BLUE"]),
      ("Fruits", ["MANGO", "PEAR", "PLUM", "ORANGE"]),
      ("Study methods", ["FLASHCARDS", "POMODORO", "OUTLINE", "REVIEW"]),
      ("Essay types", ["PERSUASIVE", "NARRATIVE", "EXPOSITORY", "COMPARE"])]),
 (3, [("Weather", ["RAIN", "SNOW", "HAIL", "FOG"]),
      ("Birds", ["ROBIN", "CROW", "HERON", "FINCH"]),
      ("Streaming services", ["HULU", "MAX", "PEACOCK", "TUBI"]),
      ("Things with rings", ["SATURN", "TREE", "PHONE", "BOXER"])]),
 (4, [("At a lecture", ["SLIDES", "PODIUM", "PROJECTOR", "HANDOUT"]),
      ("___ point", ["POWER", "BULLET", "CHECK", "TALKING"]),
      ("Sound like numbers", ["WON", "TOO", "FOR", "ATE"]),
      ("Hiding a body part", ["SHINDIG", "LEGEND", "CHINA", "HEARTH"])]),
 (2, [("Ramen add-ins", ["EGG", "SCALLION", "NORI", "CORN"]),
      ("Gym machines", ["TREADMILL", "ROWER", "ELLIPTICAL", "BIKE"]),
      ("Sources you cite", ["BOOK", "JOURNAL", "WEBSITE", "INTERVIEW"]),
      ("Phone noises", ["BUZZ", "DING", "BEEP", "CHIME"])]),
 (3, [("Bed parts", ["FRAME", "MATTRESS", "HEADBOARD", "SLAT"]),
      ("Glasses parts", ["LENS", "BRIDGE", "TEMPLE", "HINGE"]),
      ("___ sheet", ["SPREAD", "CHEAT", "BALANCE", "FACT"]),
      ("Things you can crash", ["PARTY", "CAR", "COMPUTER", "COURSE"])]),
 (3, [("Study snacks", ["PRETZELS", "TRAILMIX", "GRAPES", "POPCORN"]),
      ("Things you take", ["NOTES", "BREAK", "SHOWER", "CHANCE"]),
      ("Things that pop", ["BALLOON", "BUBBLE", "QUIZ", "COLLAR"]),
      ("Baseball", ["HOMER", "STEAL", "WALK", "STRIKE"])]),
 (4, [("Campus jobs", ["TUTOR", "BARISTA", "LIFEGUARD", "USHER"]),
      ("Finals-week feelings", ["ANXIOUS", "DRAINED", "WIRED", "FRAZZLED"]),
      ("Things you draw", ["BATH", "BLOOD", "CONCLUSION", "CURTAINS"]),
      ("Backwards, another word", ["DRAWER", "STRESSED", "LIVE", "DIAPER"])]),
 (2, [("Cheeses", ["BRIE", "FETA", "GOUDA", "SWISS"]),
      ("Ways home", ["WALK", "UBER", "BIKE", "BUS"]),
      ("Bank words", ["DEPOSIT", "BALANCE", "OVERDRAFT", "INTEREST"]),
      ("Kinds of loan", ["STUDENT", "AUTO", "PAYDAY", "HOME"])]),
 (3, [("Hairstyles", ["BANGS", "BRAID", "PONYTAIL", "BUN"]),
      ("In a citation", ["AUTHOR", "TITLE", "YEAR", "PUBLISHER"]),
      ("Deadline words", ["DUE", "LATE", "EXTENSION", "PENALTY"]),
      ("Palindromes", ["LEVEL", "KAYAK", "NOON", "RADAR"])]),
 (3, [("Laundry", ["DETERGENT", "DRYER", "LINT", "HAMPER"]),
      ("Class formats", ["SEMINAR", "LAB", "LECTURE", "STUDIO"]),
      ("Dog breeds", ["BEAGLE", "POODLE", "BOXER", "HUSKY"]),
      ("Things you fold", ["LAUNDRY", "CARDS", "PAPER", "ARMS"])]),
 (2, [("Farm", ["BARN", "TRACTOR", "SILO", "PLOW"]),
      ("Photo edits", ["CROP", "FILTER", "BRIGHTEN", "ROTATE"]),
      ("Slide apps", ["KEYNOTE", "CANVA", "PREZI", "SLIDES"]),
      ("Things you brew", ["COFFEE", "TEA", "BEER", "TROUBLE"])]),
 (4, [("Test-day gear", ["PENCIL", "ERASER", "CALCULATOR", "ID"]),
      ("Freshman year", ["ORIENTATION", "ROOMMATE", "DORM", "SYLLABUS"]),
      ("Things that get graded", ["ESSAYS", "EGGS", "ROADS", "LUMBER"]),
      ("Add an S in front", ["TABLE", "CARE", "HOVEL", "PACE"])]),
 (2, [("Sodas", ["COKE", "SPRITE", "FANTA", "PEPSI"]),
      ("Sleep", ["NAP", "DOZE", "SNOOZE", "CRASH"]),
      ("A party", ["BASH", "RAGER", "MIXER", "KICKBACK"]),
      ("Music genres", ["POP", "RAP", "JAZZ", "FOLK"])]),
 (3, [("Vending machine", ["CHIPS", "GUM", "COOKIES", "SODA"]),
      ("Soccer", ["GOAL", "PITCH", "CORNER", "HEADER"]),
      ("Document parts", ["FOOTER", "MARGIN", "TITLE", "BODY"]),
      ("___ screen", ["TOUCH", "SPLIT", "SMOKE", "SUN"])]),
 (3, [("Video call buttons", ["MUTE", "UNMUTE", "SHARE", "LEAVE"]),
      ("Fishing", ["ROD", "BAIT", "HOOK", "LURE"]),
      ("Social posts", ["POST", "STORY", "REEL", "DM"]),
      ("Ways to leave", ["DIP", "BOUNCE", "SPLIT", "JET"])]),
 (2, [("Majors, shortened", ["BIO", "CHEM", "ECON", "PSYCH"]),
      ("Fall", ["LEAVES", "CIDER", "SWEATER", "HARVEST"]),
      ("Gym slang", ["REPS", "SETS", "PUMP", "GAINS"]),
      ("Math words", ["PRIME", "SUM", "FACTOR", "ANGLE"])]),
 (3, [("Egg styles", ["SCRAMBLED", "POACHED", "FRIED", "BOILED"]),
      ("Ways to say tired", ["BEAT", "DRAINED", "WIPED", "ZONKED"]),
      ("Music words", ["TEMPO", "MEASURE", "REST", "PITCH"]),
      ("Baseball pitches", ["FASTBALL", "CURVE", "SLIDER", "CHANGEUP"])]),
 (3, [("Things you can skip", ["CLASS", "ROCKS", "BREAKFAST", "ADS"]),
      ("Greek life", ["RUSH", "PLEDGE", "CHAPTER", "BID"]),
      ("Auction", ["LOT", "GAVEL", "PADDLE", "RESERVE"]),
      ("Boat parts", ["STERN", "BOW", "HULL", "KEEL"])]),
 (4, [("Late-night food", ["PIZZA", "TACOS", "WINGS", "NOODLES"]),
      ("NFL teams", ["JETS", "GIANTS", "RAMS", "BEARS"]),
      ("Buffalo ___", ["BILLS", "SAUCE", "NICKEL", "CHECK"]),
      ("Hiding an animal", ["CATALOG", "SCOWL", "PIGMENT", "ANTIQUE"])]),
 (2, [("Roommate agreement", ["CHORES", "GUESTS", "QUIET", "SHARING"]),
      ("Puzzle types", ["CROSSWORD", "SUDOKU", "JIGSAW", "RIDDLE"]),
      ("Board games", ["CLUE", "RISK", "LIFE", "SORRY"]),
      ("Apologies", ["MYBAD", "PARDON", "OOPS", "FORGIVE"])]),
 (3, [("Face parts", ["NOSE", "BROW", "CHIN", "CHEEK"]),
      ("Water sports", ["SURF", "SWIM", "ROW", "DIVE"]),
      ("River words", ["BANK", "DELTA", "RAPIDS", "MOUTH"]),
      ("Online verbs", ["SCROLL", "SEARCH", "STREAM", "BROWSE"])]),
 (3, [("Kitchen", ["STOVE", "SINK", "ISLAND", "CABINET"]),
      ("Basketball", ["DUNK", "REBOUND", "ASSIST", "FOUL"]),
      ("Bar order", ["SHOT", "PINT", "DRAFT", "ROUND"]),
      ("Thesis words", ["ARGUMENT", "EVIDENCE", "CLAIM", "COUNTER"])]),
 (2, [("Phone stuff", ["CASE", "CHARGER", "SCREEN", "SIM"]),
      ("Movie words", ["TRAILER", "SEQUEL", "CAMEO", "PLOT"]),
      ("Ways to study", ["SKIM", "REREAD", "QUIZ", "TEACH"]),
      ("Law school", ["BRIEF", "TORT", "BAR", "MOOT"])]),
 (3, [("Capital cities", ["LONDON", "PARIS", "ROME", "TOKYO"]),
      ("A strong password has", ["LETTER", "NUMBER", "SYMBOL", "CAPITAL"]),
      ("Cover ___", ["STORY", "BAND", "CHARGE", "SONG"]),
      ("Number ___", ["LINE", "CRUNCHER", "ONE", "PLATE"])]),
 (3, [("Spreadsheet", ["CELL", "ROW", "COLUMN", "FORMULA"]),
      ("Biology", ["GENE", "ENZYME", "TISSUE", "ORGAN"]),
      ("Newspaper", ["HEADLINE", "BYLINE", "EDITORIAL", "OPED"]),
      ("An argument", ["QUARREL", "SPAT", "TIFF", "FEUD"])]),
 (4, [("Pixar movies", ["UP", "CARS", "COCO", "SOUL"]),
      ("Group chat verbs", ["MUTE", "LEAVE", "PIN", "REACT"]),
      ("Things with pins", ["BOWLING", "MAP", "GRENADE", "CUSHION"]),
      ("Hiding a color", ["BLUEPRINT", "REDDIT", "GOLDFISH", "PINKY"])]),
 (2, [("Coffee sizes", ["SHORT", "TALL", "GRANDE", "VENTI"]),
      ("School subjects", ["HISTORY", "PHYSICS", "ART", "LATIN"]),
      ("Basketball positions", ["CENTER", "GUARD", "FORWARD", "WING"]),
      ("Email", ["INBOX", "SPAM", "SUBJECT", "CC"])]),
 (3, [("Milks", ["WHOLE", "OAT", "ALMOND", "SOY"]),
      ("Pies", ["APPLE", "PECAN", "PUMPKIN", "CHERRY"]),
      ("Textbook verbs", ["SKIM", "ANNOTATE", "HIGHLIGHT", "DOGEAR"]),
      ("Things you wear out", ["SHOES", "WELCOME", "BATTERY", "PATIENCE"])]),
 (3, [("Bathroom", ["SINK", "MIRROR", "SHOWER", "TOILET"]),
      ("Beers", ["LAGER", "STOUT", "IPA", "PILSNER"]),
      ("Baby ___", ["STEPS", "TEETH", "TALK", "FACE"]),
      ("Things you save", ["MONEY", "SEATS", "DRAFTS", "ROOM"])]),
 (2, [("Sci-fi", ["ALIEN", "ROBOT", "LASER", "WARP"]),
      ("Yarn words", ["KNIT", "PURL", "SKEIN", "CROCHET"]),
      ("Scholarship words", ["MERIT", "GRANT", "AID", "STIPEND"]),
      ("Presidents", ["ADAMS", "TAFT", "POLK", "HAYES"])]),
 (3, [("Gym bag", ["TOWEL", "SHAKER", "LOCK", "EARBUDS"]),
      ("Door parts", ["KNOB", "HINGE", "FRAME", "JAMB"]),
      ("Elevator", ["BUTTON", "FLOOR", "LOBBY", "CABLE"]),
      ("Wrestling", ["PIN", "HOLD", "TAKEDOWN", "MAT"])]),
 (4, [("Stationery", ["TAPE", "GLUE", "STAPLER", "CLIP"]),
      ("Browser tab verbs", ["OPEN", "CLOSE", "PIN", "MUTE"]),
      ("___-up exercises", ["PULL", "PUSH", "SIT", "CHIN"]),
      ("Sound like letters", ["BEE", "SEA", "TEA", "JAY"])]),
 (3, [("Yoga class", ["FLOW", "POSE", "BREATH", "MAT"]),
      ("Pirate", ["PLANK", "PARROT", "EYEPATCH", "PLUNDER"]),
      ("Rap words", ["BEAT", "BARS", "VERSE", "HOOK"]),
      ("Things you can bend", ["RULES", "KNEE", "WIRE", "TRUTH"])]),
 (2, [("Study playlist", ["LOFI", "JAZZ", "AMBIENT", "PIANO"]),
      ("Restaurant staff", ["HOST", "CHEF", "BUSSER", "BARTENDER"]),
      ("TV", ["REMOTE", "EPISODE", "RERUN", "PILOT"]),
      ("Chat app words", ["SERVER", "CHANNEL", "ROLE", "NITRO"])]),
 (3, [("Doctor visit", ["COPAY", "REFILL", "CHECKUP", "SCRIPT"]),
      ("Hair salon", ["TRIM", "FADE", "DYE", "PERM"]),
      ("Jeans", ["SKINNY", "BOOTCUT", "FLARE", "MOM"]),
      ("Screenplay", ["SCENE", "ACT", "DIALOGUE", "CUT"])]),
 (3, [("Beach", ["SAND", "WAVE", "SHELL", "TIDE"]),
      ("Roommate wake-ups", ["ALARM", "SNORE", "LIGHT", "VACUUM"]),
      ("On a wrist", ["WATCH", "BRACELET", "CUFF", "SLEEVE"]),
      ("Start with a silent letter", ["KNIFE", "GNOME", "WRIST", "PSALM"])]),
 (4, [("Essay stages", ["OUTLINE", "DRAFT", "REVISE", "PROOF"]),
      ("A cashier hands you", ["RECEIPT", "CHANGE", "BAG", "SMILE"]),
      ("Boxing", ["JAB", "HOOK", "BOUT", "ROUND"]),
      ("Hiding a number", ["TENSION", "WONDER", "FREIGHT", "CANINE"])]),
 (2, [("Semester rhythm", ["SYLLABUS", "MIDTERMS", "FINALS", "BREAK"]),
      ("Coffee gear", ["GRINDER", "KETTLE", "PRESS", "FILTER"]),
      ("Press ___", ["RELEASE", "CONFERENCE", "BOX", "PASS"]),
      ("Kinds of pass", ["HALL", "BOARDING", "DAY", "BACKSTAGE"])]),
 (3, [("Ways to say no", ["NAH", "NOPE", "PASS", "NEGATIVE"]),
      ("Spring break", ["BEACH", "ROADTRIP", "TAN", "SUNSCREEN"]),
      ("Colors", ["BEIGE", "TEAL", "MAROON", "NAVY"]),
      ("Military branches", ["ARMY", "MARINES", "AIRFORCE", "COASTGUARD"])]),
 (3, [("Trivia night", ["ROUND", "BUZZER", "TEAM", "CATEGORY"]),
      ("Round things", ["PIZZA", "COIN", "CLOCK", "PLATE"]),
      ("___ plate", ["TECTONIC", "LICENSE", "HOME", "DINNER"]),
      ("Run ___", ["WAY", "TIME", "DOWN", "OFF"])]),
 (2, [("Dorm cooking", ["MICROWAVE", "RAMEN", "TOASTER", "MUG"]),
      ("Coffee words", ["ROAST", "BREW", "GRIND", "BLEND"]),
      ("Comedy", ["STANDUP", "SKETCH", "IMPROV", "BIT"]),
      ("Horse gear", ["SADDLE", "REIN", "STIRRUP", "HOOF"])]),
 (3, [("Office hours", ["QUESTION", "PROFESSOR", "DOOR", "SIGNUP"]),
      ("Things you hold", ["BREATH", "GRUDGE", "HANDS", "PHONE"]),
      ("Bookstore", ["TEXTBOOK", "RECEIPT", "BUYBACK", "RENTAL"]),
      ("Car words", ["LEASE", "MILEAGE", "TRUNK", "HOOD"])]),
 (4, [("Campus tour", ["GUIDE", "WALK", "BROCHURE", "QUESTIONS"]),
      ("Shoe parts", ["LACE", "HEEL", "TONGUE", "INSOLE"]),
      ("Fish", ["PERCH", "PIKE", "CARP", "SOLE"]),
      ("Hiding RING", ["EARRING", "HERRING", "STRING", "BORING"])]),
 (2, [("Finals week", ["CRAM", "COFFEE", "STRESS", "LIBRARY"]),
      ("Fitness classes", ["SPIN", "ZUMBA", "BARRE", "PILATES"]),
      ("Bike parts", ["PEDAL", "CHAIN", "SPOKE", "SADDLE"]),
      ("Spin ___", ["CLASS", "DOCTOR", "CYCLE", "OFF"])]),
 (3, [("Rideshare", ["PICKUP", "DRIVER", "RATING", "TIP"]),
      ("Golf", ["PUTTER", "BIRDIE", "FAIRWAY", "CADDIE"]),
      ("Things with tips", ["PEN", "ARROW", "ICEBERG", "TONGUE"]),
      ("Rating scales", ["STARS", "LETTERS", "PERCENT", "THUMBS"])]),
 (3, [("Excuses", ["TRAFFIC", "ALARM", "WIFI", "PRINTER"]),
      ("Jam ___", ["SESSION", "BAND", "PACKED", "JAR"]),
      ("At the mall", ["OUTLET", "KIOSK", "FOODCOURT", "ANCHOR"]),
      ("Newsroom", ["REPORTER", "SEGMENT", "BREAKING", "DESK"])]),
 (2, [("Skincare", ["SERUM", "TONER", "MOISTURIZER", "SPF"]),
      ("Goalie gear", ["GLOVE", "PADS", "NET", "MASK"]),
      ("Printer", ["INK", "PAPER", "TRAY", "JAM"]),
      ("Semester goals", ["GPA", "SLEEP", "GYM", "SAVE"])]),
 (3, [("Study buddy traits", ["PATIENT", "PUNCTUAL", "FOCUSED", "CURIOUS"]),
      ("Hospital", ["NURSE", "WARD", "GURNEY", "SCRUBS"]),
      ("Things you scrub", ["FLOOR", "DISHES", "TUB", "DECK"]),
      ("Game ___", ["PLAN", "NIGHT", "CHANGER", "FACE"])]),
]
