"""Weave themes (a Strands-type game), hand-written.

Each theme is (theme line, spanning word, [candidate words]). The board is 6 wide
and 8 tall, 48 letters. gen.py picks a set of candidates whose letters, with the
spanning word, add up to exactly 48, then tiles the board with them: every word
is one path through touching letters (sideways, up and down, or diagonal), every
letter belongs to exactly one word, and the spanning word touches two opposite
sides of the board. Candidates are 4 to 11 letters; give eight or more so the
picker has room.
"""

WEAVES = [
 ("Coffee run", "COFFEESHOP",
  ["LATTE", "MOCHA", "ESPRESSO", "BARISTA", "BEANS", "ROAST", "CREAM", "SUGAR", "FOAM", "DECAF", "GRINDER"]),
 ("Finals week", "ALLNIGHTER",
  ["CRAM", "STRESS", "COFFEE", "LIBRARY", "REVIEW", "NOTES", "EXAM", "PANIC", "STUDY", "FLASHCARDS", "DEADLINE"]),
 ("In the dorm", "ROOMMATES",
  ["BUNK", "MINIFRIDGE", "POSTER", "LAUNDRY", "MICROWAVE", "DESK", "LAMP", "HAMPER", "PILLOW", "RUG", "SHELF"]),
 ("Gym day", "WORKOUTPLAN",
  ["SQUAT", "TREADMILL", "DUMBBELL", "YOGA", "CARDIO", "PLANK", "LUNGE", "BURPEE", "ROWING", "STRETCH", "PUSHUP"]),
 ("Pizza night", "PIZZAPARTY",
  ["CRUST", "SLICE", "PEPPERONI", "MUSHROOM", "CHEESE", "SAUCE", "OLIVE", "ONION", "BASIL", "DOUGH", "OVEN"]),
 ("Road trip", "ROADTRIP",
  ["SNACKS", "PLAYLIST", "GASSTATION", "MOTEL", "HIGHWAY", "DETOUR", "SUNROOF", "RESTSTOP", "MILES", "MAPS", "TOLL"]),
 ("Ramen bowl", "RAMENSHOP",
  ["BROTH", "NOODLE", "PORK", "SCALLION", "MISO", "NORI", "GINGER", "GARLIC", "TOFU", "SPICY", "CHILI", "EGGS"]),
 ("Job hunt", "INTERVIEW",
  ["RESUME", "COVERLETTER", "NETWORKING", "OFFER", "SALARY", "RECRUITER", "INTERN", "PORTFOLIO", "REFERENCE", "SUIT", "HANDSHAKE"]),
 ("Rainy day", "UMBRELLA",
  ["PUDDLE", "RAINCOAT", "THUNDER", "DRIZZLE", "STORM", "CLOUDS", "BOOTS", "GUTTER", "SPLASH", "MIST", "DAMP"]),
 ("Movie night", "BLOCKBUSTER",
  ["POPCORN", "TRAILER", "SEQUEL", "TICKET", "SCREEN", "ACTOR", "PLOT", "CAMEO", "CREDITS", "PREMIERE", "SODA"]),
 ("Breakfast", "PANCAKES",
  ["WAFFLE", "BACON", "OMELET", "TOAST", "CEREAL", "SYRUP", "YOGURT", "GRANOLA", "BAGEL", "JUICE", "EGGS"]),
 ("Chess", "CHECKMATE",
  ["PAWN", "ROOK", "BISHOP", "KNIGHT", "QUEEN", "CASTLE", "GAMBIT", "STALEMATE", "BOARD", "OPENING", "KING"]),
 ("Space", "SOLARSYSTEM",
  ["PLANET", "COMET", "ORBIT", "ROCKET", "NEBULA", "GALAXY", "CRATER", "METEOR", "SATURN", "JUPITER", "MOON"]),
 ("Beach day", "SUNSCREEN",
  ["TOWEL", "WAVES", "SANDCASTLE", "SHELL", "SURF", "TIDE", "LIFEGUARD", "FLIPFLOPS", "COOLER", "SEAGULL", "SAND"]),
 ("Money", "BUDGETING",
  ["SAVINGS", "RENT", "DEBIT", "CREDIT", "INCOME", "EXPENSE", "COUPON", "CHECKING", "INVEST", "LOAN", "CASH"]),
 ("Library", "STUDYSPOT",
  ["SHELF", "QUIET", "CATALOG", "LIBRARIAN", "DESK", "OVERDUE", "BORROW", "ARCHIVE", "STACKS", "CARREL", "BOOKS"]),
 ("Halloween", "TRICKORTREAT",
  ["PUMPKIN", "GHOST", "WITCH", "COSTUME", "CANDY", "SKELETON", "HAUNTED", "SPIDER", "VAMPIRE", "MASK", "BATS"]),
 ("On a bike", "TWOWHEELS",
  ["PEDAL", "CHAIN", "SPOKE", "SADDLE", "HELMET", "BRAKE", "GEAR", "TIRE", "BASKET", "HANDLEBAR", "BELL"]),
 ("Bakery", "FRESHBAKED",
  ["CROISSANT", "MUFFIN", "SCONE", "BAGUETTE", "DONUT", "BROWNIE", "COOKIE", "DANISH", "LOAF", "PASTRY", "TART"]),
 ("Music", "PLAYLIST",
  ["CHORUS", "VERSE", "MELODY", "RHYTHM", "TEMPO", "LYRICS", "BRIDGE", "HOOK", "ALBUM", "SINGLE", "BEAT"]),
 ("Garden", "GREENTHUMB",
  ["SHOVEL", "SEEDS", "COMPOST", "WATER", "SPROUT", "WEEDS", "TROWEL", "MULCH", "BLOOM", "HOSE", "SOIL"]),
 ("Weather report", "FORECAST",
  ["SUNNY", "CLOUDY", "BREEZE", "HUMID", "FROST", "HAIL", "THUNDER", "DRIZZLE", "WINDY", "SLEET", "FOGGY"]),
 ("Kitchen drawer", "MEALPREP",
  ["SPATULA", "SKILLET", "WHISK", "LADLE", "BLENDER", "OVEN", "GRATER", "TONGS", "COLANDER", "PEELER", "KNIFE"]),
 ("Camping", "CAMPFIRE",
  ["TENT", "SMORES", "LANTERN", "TRAIL", "MARSHMALLOW", "CANTEEN", "COMPASS", "FIREWOOD", "HIKING", "STARS", "BUGSPRAY"]),
 ("Airport", "BOARDINGPASS",
  ["GATE", "LUGGAGE", "TERMINAL", "SECURITY", "CARRYON", "LAYOVER", "PILOT", "RUNWAY", "CUSTOMS", "TAKEOFF", "SEAT"]),
 ("Doctor visit", "CHECKUP",
  ["STETHOSCOPE", "NURSE", "VACCINE", "SCRUBS", "BANDAGE", "XRAY", "PULSE", "CLINIC", "COPAY", "REFILL", "CHART"]),
 ("Phone", "SMARTPHONE",
  ["CHARGER", "SCREEN", "SELFIE", "RINGTONE", "BATTERY", "APPS", "TEXT", "EMOJI", "CAMERA", "SWIPE", "CASE"]),
 ("Football", "TOUCHDOWN",
  ["HELMET", "TACKLE", "HUDDLE", "FUMBLE", "KICKOFF", "QUARTERBACK", "ENDZONE", "PUNT", "BLITZ", "FIELDGOAL", "SNAP"]),
 ("Basketball", "SLAMDUNK",
  ["DRIBBLE", "REBOUND", "LAYUP", "ASSIST", "BUZZER", "FREETHROW", "SWISH", "COURT", "HOOP", "TIPOFF", "FOUL"]),
 ("Soccer", "PENALTYKICK",
  ["GOALIE", "HEADER", "CORNER", "OFFSIDE", "MIDFIELD", "CLEATS", "WHISTLE", "PITCH", "DRIBBLE", "STRIKER", "NET"]),
 ("Detective", "WHODUNIT",
  ["CLUE", "SUSPECT", "ALIBI", "MOTIVE", "WITNESS", "EVIDENCE", "SLEUTH", "CULPRIT", "FINGERPRINT", "MYSTERY", "CASE"]),
 ("Sushi", "SUSHIROLL",
  ["SALMON", "WASABI", "GINGER", "NORI", "RICE", "TUNA", "AVOCADO", "CHOPSTICKS", "TEMPURA", "EDAMAME", "SOY"]),
 ("Ice cream", "ICECREAMSHOP",
  ["SCOOP", "CONE", "SPRINKLES", "VANILLA", "FUDGE", "CHERRY", "WAFFLE", "MINT", "SORBET", "PISTACHIO", "SWIRL"]),
 ("Wedding", "HONEYMOON",
  ["BRIDE", "GROOM", "BOUQUET", "VOWS", "TOAST", "RING", "VEIL", "CAKE", "RECEPTION", "AISLE", "DANCE"]),
 ("Winter", "SNOWSTORM",
  ["MITTENS", "SCARF", "SLEDDING", "ICICLE", "COCOA", "FROST", "BLIZZARD", "SHOVEL", "FLURRY", "SKATE", "PARKA"]),
 ("Birthday", "CELEBRATION",
  ["CANDLES", "BALLOON", "CAKE", "PRESENT", "WISH", "PARTY", "CONFETTI", "CARD", "FROSTING", "GUESTS", "SONG"]),
 ("Farm", "BARNYARD",
  ["TRACTOR", "ROOSTER", "HARVEST", "SILO", "PLOW", "GOAT", "HAYSTACK", "PASTURE", "FENCE", "PIGLET", "COWS"]),
 ("Under the sea", "CORALREEF",
  ["DOLPHIN", "OCTOPUS", "SEAWEED", "SHARK", "CLAM", "TURTLE", "ANEMONE", "SEAHORSE", "STARFISH", "KELP", "CRAB"]),
 ("Circus", "RINGMASTER",
  ["CLOWN", "TRAPEZE", "JUGGLER", "ACROBAT", "TIGHTROPE", "ELEPHANT", "TENT", "CANNON", "STILTS", "POPCORN", "LION"]),
 ("Superhero", "SECRETIDENTITY",
  ["CAPE", "MASK", "VILLAIN", "SIDEKICK", "POWERS", "CITY", "LAIR", "HERO", "COMIC", "RESCUE", "GADGET"]),
 ("Game night", "BOARDGAMES",
  ["DICE", "TOKEN", "CARDS", "TIMER", "SPINNER", "PAWN", "SCORE", "TURN", "TRIVIA", "RULES", "PIECES"]),
 ("Thanksgiving", "TURKEYDINNER",
  ["STUFFING", "GRAVY", "CRANBERRY", "YAMS", "PARADE", "LEFTOVERS", "FEAST", "ROLLS", "PILGRIM", "PIES", "NAP"]),
 ("Photography", "SNAPSHOT",
  ["LENS", "FOCUS", "FLASH", "TRIPOD", "EXPOSURE", "SHUTTER", "FILTER", "ANGLE", "PORTRAIT", "ZOOM", "FRAME"]),
 ("Dentist", "TOOTHBRUSH",
  ["FLOSS", "CAVITY", "MOLAR", "ENAMEL", "PLAQUE", "BRACES", "RINSE", "GUMS", "FILLING", "SMILE", "DRILL"]),
 ("Laundry day", "SPINCYCLE",
  ["DETERGENT", "DRYER", "LINT", "HAMPER", "FOLD", "SOCKS", "STAIN", "RINSE", "BLEACH", "SOFTENER", "IRON"]),
 ("Newspaper", "FRONTPAGE",
  ["HEADLINE", "EDITOR", "COLUMN", "BYLINE", "REPORTER", "DEADLINE", "PRINT", "SCOOP", "OPINION", "COMICS", "PRESS"]),
 ("Theater", "OPENINGNIGHT",
  ["STAGE", "CURTAIN", "ACTOR", "SCRIPT", "SPOTLIGHT", "ENCORE", "PROPS", "USHER", "REHEARSE", "PLAYBILL", "CAST"]),
 ("Under the hood", "ROADREADY",
  ["ENGINE", "BRAKES", "TIRES", "WIPERS", "TRUNK", "HEADLIGHT", "GEARSHIFT", "BUMPER", "MIRROR", "HORN", "FUEL"]),
 ("Bank", "SAVINGSACCOUNT",
  ["DEPOSIT", "TELLER", "VAULT", "INTEREST", "BALANCE", "CHECK", "LOAN", "WITHDRAW", "BRANCH", "CARD", "PIN"]),
 ("Mail", "POSTOFFICE",
  ["STAMP", "ENVELOPE", "PARCEL", "LETTER", "ADDRESS", "POSTCARD", "MAILBOX", "SORTING", "DELIVERY", "PACKAGE", "ZIPCODE"]),
 ("Volcano", "ERUPTION",
  ["LAVA", "MAGMA", "CRATER", "VENT", "PUMICE", "CALDERA", "TREMOR", "SMOKE", "ASHES", "STEAM", "FISSURE"]),
 ("Baseball", "GRANDSLAM",
  ["PITCHER", "BATTER", "INNING", "DUGOUT", "STRIKE", "OUTFIELD", "BULLPEN", "CATCHER", "UMPIRE", "GLOVE", "STEAL"]),
 ("Tea time", "TEAKETTLE",
  ["CHAMOMILE", "STEEP", "EARLGREY", "HONEY", "MATCHA", "SAUCER", "TEAPOT", "OOLONG", "BISCUIT", "LEMON", "CHAI"]),
 ("Hiking", "TRAILHEAD",
  ["SUMMIT", "BACKPACK", "COMPASS", "SWITCHBACK", "BLISTER", "CANTEEN", "RIDGE", "OVERLOOK", "BOOTS", "TRAILMIX", "CREEK"]),
 ("Bees", "HONEYCOMB",
  ["POLLEN", "NECTAR", "HIVE", "QUEEN", "DRONE", "SWARM", "WAGGLE", "BUZZ", "STINGER", "WORKER", "FLOWER"]),
 ("Sleep", "GOODNIGHT",
  ["PILLOW", "BLANKET", "DREAM", "SNORE", "ALARM", "NAP", "YAWN", "PAJAMAS", "MATTRESS", "LULLABY", "REM"]),
 ("Group project", "TEAMWORK",
  ["DEADLINE", "SLIDES", "MEETING", "AGENDA", "DIVIDE", "PRESENT", "FEEDBACK", "DRAFT", "RUBRIC", "PEER", "TASKS"]),
]
