LESSON = dict(
    id='ppl-12', track='people', minutes=3,
    title='How to leave a conversation',
    blurb="Almost no conversation ends when both people want it to. You'll see the 2021 study behind that, the three-move exit that feels kind, and the lines that work at a party.",
    takeaway='Signal, appreciate, exit to somewhere. They wanted out too.',
    cards=[
        dict(kind='image', src='p01-stuck', eyebrow='Stuck',
             body="You've been talking to someone at a party for twenty minutes, and it was good for ten. Now you're both nodding. Neither of you knows how to stop, so it goes on, and both of you are thinking the same thing.",
             paint='A crowded house party at night, warm string lights, two college students standing by a wall with drinks, both smiling politely and nodding, a slightly glazed look on each, other guests blurred behind them. Exactly two people in focus, background figures soft and uncounted. No words on anything. The card says: it was good for ten minutes, now you are both nodding and neither knows how to stop.'),
        dict(kind='image', src='fig-02-study', eyebrow='The study',
             body='In 2021, Adam Mastroianni and colleagues measured hundreds of conversations and found only about 2% ended when both people wanted them to. Most people wanted out earlier than the other guessed, and the other person felt the same.'),
        dict(kind='image', src='fig-03-mismatch', eyebrow='Nobody can tell',
             body="People also guessed wrong, by a lot, about when the other person wanted to stop. So the awkward feeling is shared and invisible. Ending the conversation isn't rude. It's a favour to both of you, and usually a relief."),
        dict(kind='image', src='fig-04-three-moves', eyebrow='Three moves',
             body="Signal, appreciate, exit. 'Before I go.' 'It was great hearing about your trip.' 'I'm going to find a drink.' Ten seconds, said with a smile, and it never lands as rude, because everyone knows the shape."),
        dict(kind='image', src='p05-somewhere', eyebrow='The exit needs a place',
             body="The exit works when it goes somewhere: to get food, to say hi to someone, to the bathroom, to the train. 'I'll let you go' works too, because it hands them the exit instead, and most people take it gratefully.",
             paint='The same party: one of the two college students now half-turned away with a friendly wave and a smile, pointing toward a kitchen doorway full of warm light, the other smiling back and raising their cup. Exactly two people in focus, background soft. No words anywhere. The card says: the exit works when it goes somewhere.'),
        dict(kind='image', src='fig-06-lines', eyebrow='Lines that work',
             body="'I'm going to do a lap.' 'I promised I'd find Sam.' 'I need to head out, but this was fun.' 'Let's talk again, I want to hear how the interview goes.' Pick two, keep them, and stop inventing new ones at the party."),
        dict(kind='image', src='p07-handoff', eyebrow='Hand them off',
             body="At a party, the kindest exit is an introduction: 'You two should talk, you both did the Spain program.' Now they have someone and you're free. Everyone wins, and it makes you the person who connects people.",
             paint="A living room party, a college student with one hand on a friend's shoulder introducing them to a third person, the two new acquaintances turning to each other with bright, curious faces, string lights, a couch behind. Exactly three people. No words on anything. The card says: the kindest exit is an introduction."),
        dict(kind='image', src='fig-08-dont', eyebrow='What not to do',
             body="Don't fade away mid-sentence, don't fake a phone call, and don't check your phone until they get the hint. All three tell them they were boring. The three moves tell them they weren't, and they take less time."),
        dict(kind='image', src='p09-relief', eyebrow='Relief, both ways',
             body="Try it once and watch their shoulders drop when you say 'before I go'. They wanted out too. The catch is you'll misjudge it sometimes, and even then a warm exit beats twenty more minutes of nodding.",
             paint="Close view of two college students at the end of a chat on a campus path, both visibly relaxed, one mid-goodbye with a small wave, the other's shoulders dropped in easy relief, a warm smile each, golden hour light. Exactly two people. No words anywhere. The card says: watch their shoulders drop when you say before I go."),
        dict(kind='key', body='Signal, appreciate, exit to somewhere. They wanted out too. Say it with a smile.'),
        dict(kind='check',
             question="You've been talking for twenty minutes and want to go. What's the best move?",
             choices=["'Before I go, great hearing about Spain. I'm going to find Sam.'", 'Check your phone and drift, so it ends without anyone saying so', "Keep going until they end it, so you don't come across as rude"],
             answer=0,
             why='The study says they probably wanted out too, and drifting or waiting both feel worse to them than a clean, warm goodbye.'),
    ])
