LESSON = dict(
    id="work-8", track="work", minutes=3,
    title="The cold email that gets a reply",
    blurb="Most emails to strangers get no answer, and the length is why. Here's the five-line shape, the ask that gets a yes, and when to follow up.",
    takeaway="You learned to write to a stranger so that replying is the easy option.",
    cards=[
        dict(kind="image", src="p01-draft", eyebrow="The blank email",
             body="You want to ask someone for advice, an internship, ten minutes. You write four paragraphs about yourself. Then you delete it. Then you never send it. Here is the version that gets sent.",
             paint="A college student at a desk at night, laptop open, chin in hand, staring at a screen that shows only a mostly blank page with a soft grey block of text and a blinking cursor (no readable words), a cold mug beside them, a crumpled note on the desk. Exactly one person. No words anywhere. The card says: you write four paragraphs about yourself, then delete it, then never send it."),
        dict(kind="image", src="fig-02-what-it-is", eyebrow="What a cold email is",
             body="A cold email is a message to someone who does not know you. They owe you nothing. So the email has one job: make replying easier than ignoring. Short does that. Specific does that."),
        dict(kind="image", src="fig-03-five-lines", eyebrow="Five lines",
             body="Line one, who you are. Line two, why them, specifically. Line three, the ask, one small thing. Line four, make yes easy. Line five, thanks. Under a hundred words."),
        dict(kind="image", src="fig-04-before-after", eyebrow="Before and after",
             body="'I'd love to pick your brain sometime' is a chore to answer. 'Could I ask two questions about your first year? Fifteen minutes, any day next week' is a yes or a no."),
        dict(kind="image", src="p05-why-them", eyebrow="Why them",
             body="Line two is where most emails die. 'I admire your work' is nothing. 'Your talk on pricing changed how I did my project' is something. It proves this did not go to forty people.",
             paint="A college student in the back row of a small lecture hall, leaning forward, listening hard to a speaker at the front and scribbling one line in a notebook, the speaker mid-gesture beside a screen that shows only coloured shapes. Exactly two people. No words on the screen or notebook. The card says: line two proves you actually paid attention to their work."),
        dict(kind="image", src="fig-06-subject", eyebrow="The subject line",
             body="The subject decides if it opens. Say what it is. 'Two questions from a Purdue junior' beats 'Hello' or 'Quick question'. Plain, honest, and it shows the size of the ask."),
        dict(kind="image", src="p07-send", eyebrow="Send it",
             body="Send it on a weekday morning. Then do nothing. Do not refresh. Do not send a second one on day two. Busy people answer in bursts, often a week later.",
             paint="A college student on a sunny campus bench in the morning, phone in hand, thumb just lifting off the screen after pressing send, a relieved exhale on their face, a coffee beside them, trees and a path behind. Exactly one person. The phone screen shows only a soft blank page, no words. The card says: send it on a weekday morning, then do nothing."),
        dict(kind="image", src="fig-08-follow-up", eyebrow="One follow-up",
             body="No reply in seven days? Reply to your own email with two lines. 'Bumping this in case it got buried. Totally understand if not.' One follow-up, then stop. Silence is an answer too."),
        dict(kind="image", src="p09-coffee", eyebrow="When they say yes",
             body="Be on time, ask your two questions, stop at fifteen minutes. Then send a thank-you the same day, with the one thing you will do because of it. That is how a stranger becomes a contact.",
             paint="A bright cafe table by a window: a college student with a small notebook listening closely to a professional in their thirties who is talking with open hands, two coffees between them, morning light. Exactly two people. No menu boards, logos, or words. The card says: be on time, ask your two questions, stop at fifteen minutes."),
        dict(kind="key", body="Five lines, one small ask, make yes easy. Follow up once after a week, then stop."),
        dict(kind="check",
             question="Which ask is most likely to get a reply from a busy stranger?",
             choices=["'Two questions about your first year. Fifteen minutes next week?'",
                      "'I'd love to pick your brain whenever you have some free time.'",
                      "'Could you look over my resume and tell me what you think of it?'"],
             answer=0,
             why="It is small, timed, and specific, so they can say yes without planning anything. The other two hand them work or leave the size of the ask open."),
    ])
