LESSON = dict(
    id='work-10', track='work', minutes=3,
    title="'Tell me about yourself' has a shape",
    blurb="It's the first question in almost every interview, and most people answer it by reading their resume aloud. You'll see the three-part shape, the 220-word budget, and the last line that hands the conversation back.",
    takeaway='Present, past, future, in ninety seconds, ending on why this role.',
    cards=[
        dict(kind='image', src='p01-chair', eyebrow='The first question',
             body="You sit down, they smile, and they say 'So, tell me about yourself.' It sounds like small talk and it's the interview. Most people answer with their resume, read aloud, slowly, and the interviewer has already read it.",
             paint='An interview room: a college-age candidate just sitting down in a chair, hands on knees, a polite nervous smile, across from two interviewers at a table who are smiling warmly, one with a pen ready. Bright window light, a plant. Exactly three people. No papers with words, no name plates. The card says: they smile and say tell me about yourself, and it is the interview.'),
        dict(kind='image', src='fig-02-what-it-is', eyebrow='What it is',
             body="The question really means 'why are you here, and can you explain yourself?' They want the story that connects the lines on the resume, told by someone who can talk. That's a different thing from the resume itself."),
        dict(kind='image', src='fig-03-shape', eyebrow='Present, past, future',
             body="Three parts. Present: what you do now, in one line. Past: the two things that led here. Future: why this role is the next step. That order every time, because it ends on the job they're hiring for."),
        dict(kind='image', src='fig-04-length', eyebrow='Ninety seconds',
             body="People talk at about 150 words a minute, so ninety seconds is about 220 words. That's your budget. Longer and they stop listening. Shorter and it sounds like you didn't prepare, which they'll assume about everything else too."),
        dict(kind='image', src='p05-practice', eyebrow='Say it out loud',
             body='Write it, then say it to a wall ten times, then to a friend. It has to sound like talking, not reading. Around the tenth time it stops being a script and starts being something you believe.',
             paint='A college student standing in a small dorm room talking out loud to a mirror on the wardrobe door, one hand gesturing, a phone propped on the desk recording, evening lamplight, a bed and posters that are only coloured shapes. Exactly one person, plus their reflection. No words anywhere. The card says: say it to a wall ten times, then to a friend.'),
        dict(kind='image', src='fig-06-example', eyebrow='An example',
             body="'I'm a junior in econ. Last summer I ran the data for a campus food pantry, which is where I got hooked on analysis. This role is that, full time.' Forty words: present, past, future, and it took twenty seconds."),
        dict(kind='image', src='fig-07-last-line', eyebrow='The last line',
             body="End on why this role: 'And that's why this one caught my eye.' It hands the conversation back and says you want this job, not any job. Then stop talking, even if the silence feels long."),
        dict(kind='image', src='p08-listen', eyebrow='Then listen',
             body="The follow-up questions come from your answer, so put in it the two things you want to talk about. You aren't only answering. You're setting the table for the next thirty minutes, and they'll eat what you put out.",
             paint='The same interview room a few minutes in: the college-age candidate now relaxed and leaning slightly forward, mid-sentence with open hands, the two interviewers engaged, one nodding, one writing. Bright daylight. Exactly three people. No readable words anywhere. The card says: the follow-up questions come from your answer, so set the table.'),
        dict(kind='image', src='p09-notes', eyebrow='Every interview',
             body="This answer is the same in every interview with one line changed for the role. Build it once, keep it in your notes, update it each year. The catch: if you can't say it without the notes, it isn't ready yet.",
             paint='A college student on a train or bus by the window, earbuds in, reading a short note on their phone with a calm, ready face, a folder on their lap, city passing outside. Exactly one person. The phone shows only a soft page with grey bars, no words. The card says: build it once, keep it in your notes, change one line per role.'),
        dict(kind='key', body='Present, past, future. Ninety seconds, about 220 words. End on why this role.'),
        dict(kind='check',
             question="The interviewer says 'tell me about yourself'. What's the strongest opening?",
             choices=["'I'm a junior in econ. Last summer I ran the data for a food pantry.'", "'I grew up in Ohio, went to Westlake High, then came here for econ.'", "'Sure. Where would you like me to start, with school or with jobs?'"],
             answer=0,
             why='It starts in the present and moves to a real detail, while childhood spends the budget on nothing and asking them to choose hands back the one question you could prepare.'),
    ])
