#!/usr/bin/env python3
"""Put the cut icons into the app and regenerate the Swift tint table.

Writes, for each icon in the manifest:
  ios/Resources/Assets.xcassets/icon-<name>.imageset   1x/2x/3x PNG
  ios/Sources/IconTint.swift                           the tile colour table

Raster, not vector: the set is illustrated, not geometric, so there is no path
data to preserve. 264pt at 3x covers every place the app draws one — the largest
is the 64pt lesson cover.

Run:  python3 design/icons/cut.py && python3 design/icons/pack.py
"""
import os, sys, json, glob
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import icons as M

ROOT = os.path.dirname(os.path.dirname(HERE))
CAT = os.path.join(ROOT, "ios", "Resources", "Assets.xcassets")
PNG = os.path.join(HERE, "png")
SCALES = [("1x", 88), ("2x", 176), ("3x", 264)]
# The league badges draw up to 132pt, so they keep the whole cut canvas.
SCALES_LARGE = [("1x", 170), ("2x", 340), ("3x", 512)]

SWIFT = '''import SwiftUI

// Generated by design/icons/pack.py. Do not edit — change the icon's tint in
// design/icons/icons.py and rerun, so the tile and the object cannot disagree.

/// The six tile tints. An icon does not get to invent a seventh: a tile takes the
/// hue family of the object standing in it, and there are six families.
enum IconTint: String {
    case %(cases)s

    /// The tile fill.
    var soft: Color {
        switch self {
%(soft)s
        }
    }

    /// Which tint an icon's tile takes. An unknown name lands on sky rather than
    /// crashing, so a task category added before its art still draws a tile.
    static func of(_ icon: String) -> IconTint {
        switch icon {
%(map)s
        default: return .sky
        }
    }
}

/// One icon on its tile. The only way the app draws a content icon.
///
/// 44 in a row, 52 on a card. The corner is a constant fraction of the side, so
/// both land on the radius scale without a second rule.
struct IconTile: View {
    let icon: String
    var size: CGFloat = 44

    var body: some View {
        RoundedRectangle(cornerRadius: Theme.Radius.tile(size), style: .continuous)
            .fill(IconTint.of(icon).soft)
            .frame(width: size, height: size)
            .overlay(
                Image("icon-" + icon)
                    .resizable()
                    .scaledToFit()
                    .frame(width: size * 0.72, height: size * 0.72)
            )
            .accessibilityHidden(true)
    }
}
'''


def main():
    assert os.path.isdir(CAT), CAT
    fams = list(M.TINT)
    for name, _, _, _, _, _ in M.SET:
        src = Image.open(os.path.join(PNG, name + ".png")).convert("RGBA")
        d = os.path.join(CAT, f"icon-{name}.imageset")
        os.makedirs(d, exist_ok=True)
        for stale in glob.glob(os.path.join(d, "*.pdf")):
            os.remove(stale)
        images = []
        for tag, px in (SCALES_LARGE if name in M.LARGE else SCALES):
            f = f"icon-{name}@{tag}.png" if tag != "1x" else f"icon-{name}.png"
            src.resize((px, px), Image.LANCZOS).save(os.path.join(d, f))
            images.append({"idiom": "universal", "filename": f, "scale": tag})
        json.dump({"images": images, "info": {"author": "xcode", "version": 1}},
                  open(os.path.join(d, "Contents.json"), "w"), indent=2)

    lines = []
    for f in fams:
        names = [n for n, _, _, t, _, _ in M.SET if t == f]
        if names:
            lines.append("        case " + ", ".join(f'"{n}"' for n in names)
                         + f": return .{f}")
    body = SWIFT % {
        "cases": ", ".join(fams),
        "soft": "\n".join(f"        case .{f}: return Theme.hex(0x{M.TINT[f][1:]})"
                          for f in fams),
        "map": "\n".join(lines),
    }
    open(os.path.join(ROOT, "ios", "Sources", "IconTint.swift"), "w").write(body)
    print(f"{len(M.SET)} imagesets -> {CAT}")
    print("IconTint.swift regenerated")


if __name__ == "__main__":
    main()
