LESSON = dict(
    id="hlth-2", track="health", minutes=3,
    title="Alcohol wrecks the second half of sleep",
    blurb="Drinks make you fall asleep fast, which is why it feels like they help. Here's what happens after 3am, what it costs the next day, and the timing that softens it.",
    takeaway="You learned why a nightcap is a bad sleep aid and how to time drinks around sleep.",
    cards=[
        dict(kind="image", src="p01-out-cold", eyebrow="Out like a light",
             body="Three drinks, home by midnight, asleep in minutes. It feels like the best sleep aid there is. At 4am you are wide awake, thirsty, heart going. That is the second half.",
             paint="A college student asleep fully dressed on top of the covers of a dorm bed at night, one shoe still on, a jacket half off, mouth open, a glass of water untouched on the nightstand, dim blue light from the window. Exactly one person. No clock numbers, no labels, no words. The card says: three drinks, asleep in minutes, then wide awake at 4am."),
        dict(kind="image", src="fig-02-what-it-is", eyebrow="What it is",
             body="Alcohol is a sedative. It slows the brain, so you fall asleep faster and deeper at first. As your body clears it, the brain rebounds. Lighter sleep, more waking, less dreaming."),
        dict(kind="image", src="fig-03-two-halves", eyebrow="Two halves",
             body="The first half of the night goes deep. The second half is where it falls apart. Short wake-ups you do not remember, and much less REM, the dreaming sleep that stores what you learned."),
        dict(kind="image", src="fig-04-clearing", eyebrow="One drink an hour",
             body="Your body clears roughly one standard drink an hour. Three drinks at 11pm are gone by about 2am. That is when the rebound starts. Right in the middle of the night."),
        dict(kind="image", src="p05-next-day", eyebrow="What it costs",
             body="You slept eight hours and feel like five. Reaction time, memory and mood all take the hit. This is why the day after feels foggy even without a hangover.",
             paint="A college student in a bright morning lecture hall, slumped low in a seat with hood up, eyes half closed, sunglasses pushed up on their head, a big water bottle on the fold-out desk, other students blurred and attentive around them. Exactly one person in focus, background figures soft. No words on screens or bottles. The card says: eight hours in bed and it feels like five."),
        dict(kind="image", src="fig-06-rem", eyebrow="REM and learning",
             body="REM is when the brain files the day. Drinking after studying cuts REM, so less of what you learned gets filed. Study nights and drink nights are best kept apart."),
        dict(kind="image", src="fig-07-timing", eyebrow="Timing",
             body="Stop drinking three hours before bed. A drink at 8pm is mostly cleared by 11. The rebound happens while you are still awake, not at 4am. Same drinks, much better night."),
        dict(kind="image", src="p08-water", eyebrow="Water between",
             body="A glass of water between drinks slows the pace and softens the 4am thirst. It is the least fun advice and the most reliable. Order it with the drink, not after.",
             paint="A lively bar table with three college friends, one of them lifting a tall glass of plain water with a cheerful shrug while the other two hold pints and laugh, warm amber light, bottles behind the bar with no labels. Exactly three people. No logos, signs, or words. The card says: a glass of water between drinks, ordered with the drink, not after."),
        dict(kind="image", src="p09-trade", eyebrow="The trade",
             body="Nobody is saying never. It is a trade. Know what you are trading: the second half of tonight and the first half of tomorrow. On a Friday, fine. The night before an exam, not.",
             paint="Two college students walking home late along a quiet street under streetlights, arms around each other's shoulders, laughing, one carrying a jacket, a calm night sky, a Friday feeling. Exactly two people. No signs or words. The card says: it is a trade, fine on a Friday, not the night before an exam."),
        dict(kind="key", body="Alcohol buys a fast first half and sells the second. Stop three hours before bed."),
        dict(kind="check",
             question="Exam Thursday. A friend suggests a couple of drinks Wednesday to sleep well. What's true?",
             choices=["You'll fall asleep faster, sleep worse, and remember less",
                      "Two drinks are fine, it's only four or more that hurt sleep",
                      "Alcohol helps sleep, it's the hangover that hurts the exam"],
             answer=0,
             why="The sedative effect is real for the first half. The rebound wrecks the second half and cuts REM, which is when what you studied gets filed."),
    ])
