LESSON = dict(
    id="hlth-1", track="health", minutes=3,
    title="Caffeine has a half-life",
    blurb="A 4pm coffee is still half there at 9pm. Here's what a half-life is, why you fall asleep but sleep worse, and the cutoff time that fixes it.",
    takeaway="You learned to time caffeine by its half-life, not by how awake you feel.",
    cards=[
        dict(kind="image", src="p01-latte", eyebrow="4pm",
             body="It is 4pm and the afternoon has gone flat. So you get a coffee, and it works. At 11pm you are in bed, tired, and somehow not asleep. The coffee is still there.",
             paint="A college student at a cafe counter in the late afternoon, taking a tall paper cup of coffee from a barista, low golden sun coming through the window behind them, the student looking a bit drained but grateful. Exactly two people. No menu boards, no logos on the cup, no words anywhere. The card says: it is 4pm, the afternoon has gone flat, so you get a coffee."),
        dict(kind="image", src="fig-02-halflife", eyebrow="What a half-life is",
             body="A half-life is how long your body takes to clear half of something. For caffeine it is about five hours. Not all of it. Half. Then half of what is left, and so on."),
        dict(kind="image", src="fig-03-timeline", eyebrow="The math",
             body="A regular coffee is about 200mg of caffeine. Drink it at 4pm and 100mg is still in you at 9pm. At 2am, 50mg. That is a cup of black tea's worth, at 2am."),
        dict(kind="image", src="p04-bed", eyebrow="Not about falling asleep",
             body="You may still fall asleep. Caffeine is not only a wake-up drug. It blocks the signal that tells your brain how tired it is. So you sleep, but lighter, and you wake up less rested.",
             paint="A dark dorm bedroom at night, a college student lying in bed on their back, eyes open, staring at the ceiling, blanket half off, faint blue moonlight from the window. Exactly one person. No clock, no phone screen, no words. The card says: you may still fall asleep, but lighter, and you wake up less rested."),
        dict(kind="image", src="fig-05-adenosine", eyebrow="Adenosine",
             body="All day a chemical called adenosine piles up in your brain. That pile is what tiredness is. Caffeine parks in adenosine's spots. The pile keeps growing. You just can't feel it."),
        dict(kind="image", src="fig-06-study", eyebrow="What it costs",
             body="In one study, 400mg of caffeine six hours before bed cut sleep by about an hour. The people in the study did not notice. The sleep recording did."),
        dict(kind="image", src="p07-cutoff", eyebrow="The cutoff",
             body="Count back from bed. If lights out is at midnight, the last coffee is at 2pm. Ten hours is two half-lives. That leaves a quarter of the dose, which most people sleep through.",
             paint="A college student on a sunny campus lawn just after lunch, sitting against a tree with a coffee cup and an open textbook, high bright midday sun, short shadows, relaxed and alert. Exactly one person. No words on the book or cup, no clock. The card says: count back from bed, the last coffee is ten hours before lights out."),
        dict(kind="image", src="fig-08-doses", eyebrow="Know your dose",
             body="Not all cups are equal. A large cafe coffee is about 200mg. An energy drink can hit 160. Black tea is about 50. Decaf is close to zero. The size and the kind both matter."),
        dict(kind="image", src="p09-morning", eyebrow="Move it, don't lose it",
             body="You do not have to quit. Move it. Coffee before noon, tea after. In a week the 4pm slump shrinks, because you slept. That is the whole trick.",
             paint="A bright kitchen in the morning, a college student in a hoodie pouring coffee from a small pot into a mug, sunlight streaming in, a happy unhurried face, a bowl of fruit on the counter. Exactly one person. No words, no logos, no clock numbers. The card says: coffee before noon, tea after, and the 4pm slump shrinks because you slept."),
        dict(kind="key", body="Half of a 4pm coffee is still in you at 9pm. Make the last one ten hours before bed."),
        dict(kind="check",
             question="Lights out is at 11pm. What is the latest a regular coffee is safe for your sleep?",
             choices=["Around 1pm, ten hours before bed",
                      "Around 5pm, six hours before bed",
                      "Around 8pm, if it is a small cup"],
             answer=0,
             why="Ten hours is two half-lives, which leaves a quarter of the dose. Six hours leaves half, and the study showed that still costs about an hour of sleep."),
    ])
