LESSON = dict(
    id="phil-11", track="philosophy", minutes=3,
    title="The experience machine",
    blurb="A machine can give you any life you want, and you will never know it is fake. Most people say no. Here's the thought experiment, what the no reveals, and the twist.",
    takeaway="You learned what the experience machine shows about what you actually want.",
    cards=[
        dict(kind="image", src="p01-machine", eyebrow="The offer",
             body="Imagine a machine. Plug in, and you live any life you choose. It feels completely real. You will never know it is not. You can stay in for life. Do you plug in?",
             paint="A quiet, softly lit white room with one sleek reclining pod, its lid open, gentle glow inside, a few smooth cables running to the floor. A college-age person stands a step away from it, hand half raised, hesitating, thoughtful. Exactly one person. No screens with words, no labels, no logos. The card says: plug in and live any life you choose, it feels real, do you plug in?"),
        dict(kind="image", src="fig-02-what-it-is", eyebrow="What it is",
             body="A thought experiment is a made-up situation used to test an idea. This one is from the philosopher Robert Nozick, in 1974. The idea it tests: is feeling good the only thing that matters?"),
        dict(kind="image", src="fig-03-three-reasons", eyebrow="Most say no",
             body="Most people say no. If pleasure were all we wanted, everyone would say yes. Nozick found three things in the no. We want to do things. We want to be someone. We want contact with what is real."),
        dict(kind="image", src="p04-summit", eyebrow="Doing vs feeling",
             body="Picture climbing a mountain. The machine can give you the view and the feeling at the top. It cannot give you having climbed it. That gap is what people refuse to give up.",
             paint="A lone hiker, college-age, standing on a rocky summit at sunrise, windblown, muddy boots, hands on hips, breathing hard and grinning at a sea of clouds and distant peaks. Exactly one person. No signs, no words. The card says: the machine can give you the view and the feeling, not the having climbed it."),
        dict(kind="image", src="fig-05-feed", eyebrow="The small machine",
             body="Your phone is a weak experience machine. A feed of other people's summits gives a little of the feeling and none of the climb. It is not evil. It is just the machine, in a pocket."),
        dict(kind="image", src="fig-06-twist", eyebrow="The twist",
             body="In 2010 a philosopher flipped it. Suppose you learn you are already plugged in, and your real life is different. Would you unplug? Most people said no to that too."),
        dict(kind="image", src="fig-07-status-quo", eyebrow="What the twist shows",
             body="So part of the no is habit. People keep whatever life they already have. That is called status quo bias. Nozick's point still stands, but it is smaller than it first looked."),
        dict(kind="image", src="p08-choice", eyebrow="The useful question",
             body="You do not need a machine to use this. Ask it about any choice. Am I picking this because I want to do it, or because I want the feeling of having done it? The answers differ.",
             paint="A college student at a desk with two things in front of them: a running shoe and a phone lying face down, the student looking at the shoe with a small, deciding smile, morning light through a window. Exactly one person. No words or logos on the shoe or phone. The card says: am I picking this to do it, or for the feeling of having done it?"),
        dict(kind="image", src="p09-real", eyebrow="Contact with reality",
             body="Real things can go wrong. That is what makes them real. The machine offers a life with nothing at stake. Most people, asked plainly, would rather have the stakes.",
             paint="Two college students on a windy beach at dusk, laughing as they fail to keep a kite up, hair everywhere, one holding the tangled string, the other running, cold grey-gold light. Exactly two people. No words anywhere. The card says: real things can go wrong, and that is what makes them real."),
        dict(kind="key", body="Most people won't plug in. We want to do things and touch what's real, not only feel good."),
        dict(kind="check",
             question="The machine gives you the feeling of running a marathon, guaranteed. Most people still say no. Why?",
             choices=["They want to have actually run it, not only feel like they did",
                      "They think the machine would eventually break and leave them hurt",
                      "They believe feelings from a machine are weaker than real ones"],
             answer=0,
             why="The machine copies the feeling exactly. What it cannot copy is the doing. The no shows that doing, and contact with reality, are things we want on their own."),
    ])
