LESSON = dict(
    id="ppl-11", track="people", minutes=3,
    title="Roommate rules before the first fight",
    blurb="The dishes fight is never about the dishes. Here's the twenty-minute talk in week one, the six things to settle, and what to say when it slips.",
    takeaway="You learned to set roommate rules early, when nobody is angry yet.",
    cards=[
        dict(kind="image", src="p01-dishes", eyebrow="The dishes",
             body="Week six. The sink is full again. You say nothing, then you say it badly. Now it is a fight about dishes that is not about dishes. It is about a rule nobody said out loud.",
             paint="A small student apartment kitchen at night, a sink piled with dirty dishes, one roommate standing with arms crossed and a tight face, the other in the doorway with an annoyed shrug. Cold overhead light. Exactly two people. No words on anything. The card says: week six, the sink is full again, and it is a fight that is not about dishes."),
        dict(kind="image", src="fig-02-what-it-is", eyebrow="What a rule is",
             body="A roommate rule is a shared expectation said out loud. Unsaid, each of you has one anyway, and they are different. Every fight is two unsaid rules meeting in the kitchen."),
        dict(kind="image", src="fig-03-six-things", eyebrow="The six things",
             body="Guests, and overnight guests. Noise, and quiet hours. Cleaning, who and when. Shared food. Temperature. Bills, and who pays first. Twenty minutes in week one covers all six."),
        dict(kind="image", src="p04-talk", eyebrow="Week one, not week six",
             body="Have it in week one, over food, before anything has gone wrong. 'Can we do the boring roommate talk now so we never need to?' Nobody is angry yet. That is exactly why it works.",
             paint="Two new roommates sitting cross-legged on the floor of a half-unpacked dorm room in the evening, sharing takeout from cartons, one talking with a relaxed grin, the other laughing, moving boxes and a bare mattress behind them. Exactly two people. No words on boxes or cartons. The card says: have the boring roommate talk in week one, over food, before anything goes wrong."),
        dict(kind="image", src="fig-05-fridge", eyebrow="Write it down",
             body="Put the answers somewhere visible. A whiteboard, a note on the fridge, a shared note on your phones. Memory bends toward what suits you. A written rule does not."),
        dict(kind="image", src="fig-06-rule-not-person", eyebrow="When it slips",
             body="It will slip. Say the rule, not the person. 'We said dishes same day. Can you get those tonight?' Not 'you never clean up.' One is a reminder. The other is a fight."),
        dict(kind="image", src="p07-money", eyebrow="Money, early",
             body="Bills are where roommates end. Decide who pays the landlord, who pays for the internet, and by what day. Use an app that shows who owes what. Never let it reach two months.",
             paint="Two roommates at a kitchen table with a laptop and two phones, one pointing at the laptop screen which shows only a simple chart of coloured blocks, the other holding a bank card, both calm and businesslike, morning light. Exactly two people. No numbers or words on any screen. The card says: decide who pays what and by what day, and use an app that shows who owes."),
        dict(kind="image", src="fig-08-reset", eyebrow="The monthly reset",
             body="Once a month, five minutes. 'Anything bugging you?' Ask it before you have something to say. Small things said at five minutes never become the big thing said at midnight."),
        dict(kind="image", src="p09-ra", eyebrow="When it's not working",
             body="Some pairs do not work, and that is nobody's crime. If the talk and the reset both fail, go to the RA or housing early. A room change in October beats a bad year.",
             paint="A dorm corridor in daytime, a college student knocking on an open office door, inside a friendly resident adviser looking up from a desk with a welcoming expression, a corkboard behind with only coloured paper squares. Exactly two people. No words on the board or door. The card says: if the talk and the reset both fail, go to the RA early."),
        dict(kind="key", body="Six things in week one, written down. Say the rule, not the person, when it slips."),
        dict(kind="check",
             question="Your roommate left dishes again after you agreed on same-day. What do you say?",
             choices=["'We said same day. Can you get those tonight?'",
                      "'You never clean up after yourself, ever.'",
                      "Nothing. Just wash them and keep the peace."],
             answer=0,
             why="It names the shared rule and asks for one action. Accusing makes it about character, and silence teaches them the rule is gone."),
    ])
