LESSON = dict(
    id='hlth-6', track='health', minutes=3,
    title='Why you crash at 3pm',
    blurb="The afternoon dip is built into your body clock, and lunch makes it worse. You'll see what causes it, what a big carb lunch adds, and the three fixes in the order to try them.",
    takeaway='The dip is on the clock. Walk, then nap twenty, then light, and coffee last.',
    cards=[
        dict(kind='image', src='p01-lecture', eyebrow='The 2pm lecture',
             body="Two o'clock lecture, and by 2:40 your eyes are closing. You slept fine and you ate lunch. Nothing's wrong with you. This dip has a name and a schedule, and it's been on that schedule your whole life.",
             paint="A dim lecture hall in the early afternoon, a college student in a middle row with chin sinking toward their chest and eyelids heavy, pen slipping, the lecturer a soft shape at the front, other students blurred. Exactly one person in focus, background figures soft. No words on slides or notes. The card says: the two o'clock lecture, and by 2:40 your eyes are closing."),
        dict(kind='image', src='fig-02-wave', eyebrow='What it is',
             body='Your body clock runs a 24-hour wave of alertness with two low points, around 3am and around 2pm. Sleep researchers call the second one the post-lunch dip, and it happens even if you skip lunch. Lunch just deepens it.'),
        dict(kind='image', src='fig-03-lunch', eyebrow='What lunch adds',
             body="A big, carb-heavy lunch sends blood sugar up, then down, and the down lands right on the dip. Two waves, same time. A smaller lunch with some protein flattens the second wave, and you'll feel that by Thursday."),
        dict(kind='image', src='fig-04-coffee', eyebrow='The coffee trap',
             body="A 3pm coffee works. It's also 100mg still in you at 8pm and 50mg at 1am. The dip is a two-hour problem and the coffee is a tonight problem, so reach for it last, after the three fixes below."),
        dict(kind='image', src='p05-walk', eyebrow='Fix one: move',
             body="First, ten minutes of brisk walking. It lifts energy for about two hours, which is exactly the length of the dip. Outside if you can, for the light, and a lap of the building if you can't.",
             paint="A college student stepping out of a building's glass doors into bright early-afternoon sun, squinting happily, already walking at a brisk pace, a path and trees ahead, backpack on. Exactly one person. No signs or words on the doors. The card says: ten minutes of brisk walking lifts energy for about two hours."),
        dict(kind='image', src='fig-06-nap', eyebrow='Fix two: the 20-minute nap',
             body="If you can, nap: twenty minutes, before 3pm, alarm set. Longer and you wake up groggy from deep sleep. Later and it eats tonight. Twenty minutes is the whole trick, and the alarm isn't optional."),
        dict(kind='image', src='fig-07-light', eyebrow='Fix three: light',
             body="Bright light tells the clock it's still day. Sit by a window or step outside for five minutes. Dim rooms after lunch deepen the dip, and lecture halls are dim rooms, which explains a lot about 2:40."),
        dict(kind='image', src='p08-plan', eyebrow='Plan around it',
             body='Put the easy work at 2pm and the hard work at 10am or 4pm. Reading emails in the dip costs nothing. Writing an essay in the dip costs an hour, and the hour comes out of tonight.',
             paint='A college student at a sunny window seat in a library in the mid-afternoon, relaxed, sorting a small stack of papers into two piles with a calm, unhurried face, a laptop closed beside them. Exactly one person. The papers show only grey squiggles, no words. The card says: put the easy work at 2pm and the hard work at 10am or 4pm.'),
        dict(kind='image', src='p09-second-wind', eyebrow='The second wind',
             body="Around 5pm the wave comes back up on its own. That's the second wind, and it was always coming. The fixes just get you there without spending tonight's sleep, which the coffee would have.",
             paint='A college student at a desk in late-afternoon golden light, sitting up straight, typing with energy and a small smile, a window behind glowing orange, a plant and a water bottle. Exactly one person. The laptop screen shows only soft coloured blocks, no words. The card says: around 5pm the wave comes back up on its own.'),
        dict(kind='key', body='The dip is on the clock, and lunch deepens it. Walk, then nap 20, then light. Coffee last.'),
        dict(kind='check',
             question="It's 2:30pm and you're fading, with a big exam tomorrow. What's the best first move?",
             choices=['A ten-minute brisk walk, ideally in daylight', 'A coffee now, so you can study until midnight', 'A one-hour nap to properly catch up on sleep'],
             answer=0,
             why="The walk covers the two-hour dip and costs nothing tonight, while the coffee is still half there at 7:30pm and an hour's nap wakes you groggy."),
    ])
