LESSON = dict(
    id='work-4', track='work', minutes=3,
    title='How to read an offer letter',
    blurb="An offer letter has five parts and most people read one. You'll see what each line promises, why a 10% target bonus isn't $6,000, and the two-line reply that adds what's missing.",
    takeaway="Base is promised, bonus is hoped, and anything not in the letter isn't real yet.",
    cards=[
        dict(kind='image', src='p01-inbox', eyebrow='The moment',
             body="The offer's in your inbox and you've read it once, fast, hunting for the number. Now you want to sign tonight before it disappears. It won't. There are five parts in that letter and the salary is only one of them.",
             paint='A college student at a kitchen table in the evening, laptop open, one hand over their mouth, eyes wide, a happy shocked grin. The laptop screen shows only a soft white page with one big green button and a few grey bars (no words). A phone face down beside it. Exactly one person. The card says: the offer lands and you want to sign it tonight. Slow down.'),
        dict(kind='image', src='fig-02-five-parts', eyebrow='What it is',
             body="An offer letter is the company's written promise of a job: what you get and when you start. If something isn't in the letter, it isn't promised yet, whatever anyone said to you in the interview."),
        dict(kind='image', src='fig-03-base', eyebrow='The real number',
             body='Base salary is the only number you can count on. $60,000 a year is $5,000 a month before tax and roughly $4,000 after, depending on your state. Build your rent and your budget on the after-tax number.'),
        dict(kind='image', src='fig-04-bonus', eyebrow='The maybe number',
             body="A 10% target bonus sounds like $6,000. Target means if the company hits its goals and you hit yours. Some years it pays in full, some years nothing, and the letter doesn't say which year this is."),
        dict(kind='image', src='p05-hallway', eyebrow='Said out loud',
             body="In the interview the manager said you could work from home on Fridays, and it's not in the letter. Spoken promises leave when that manager leaves. If it matters to you, ask for it in writing before you sign anything.",
             paint='A bright office hallway. A friendly manager in their forties, mid-sentence, one hand open in a casual promise, talking to a college-age candidate who is nodding and smiling. Glass walls, plants, afternoon light. Exactly two people. No signs, badges or screens with words. The card says: the manager said Fridays from home, but it is not in the letter.'),
        dict(kind='image', src='fig-06-ask', eyebrow='Ask in writing',
             body="Asking is normal and nobody minds. One short reply does it: thank them, name the one thing, say you'll sign once it's added. Keep it warm and short, and don't pile three more requests on top of it."),
        dict(kind='image', src='p07-deadline', eyebrow='The deadline',
             body="'Please sign by Friday' is standard, and asking for a week is standard too. Pew found in 2023 that most people who asked for more when hired got some of it. A place that pulls the offer for asking has told you something.",
             paint='A college-age person sitting calmly on a dorm bed by a window, phone to their ear, relaxed posture, a small confident smile, a notebook open on their knee with a few squiggled lines. Soft morning light. Exactly one person. No words on the notebook, nothing on the phone screen. The card says: asking for a week to think is standard, and companies expect it.'),
        dict(kind='image', src='fig-08-contingent', eyebrow='The small print',
             body="Most offers are contingent, which means the job is real once a few checks clear: a background check, proof of your degree, sometimes a drug test. Until they clear, don't hand in notice anywhere else."),
        dict(kind='image', src='p09-sign', eyebrow='Then sign',
             body="Now you know what's promised, what's hoped, and what's missing. Reply with the signed letter and your start date in one line, and keep a copy. You'll want it at your first review, when someone asks what you were told.",
             paint="Close view of a tidy desk from above: a person's hand signing the bottom of a printed letter with a pen, the letter's text shown only as soft grey squiggled lines, a mug of coffee, a plant, warm lamplight. No face visible, one hand only. No real letters or numbers anywhere on the page. The card says: sign it, send it with your start date, and keep a copy."),
        dict(kind='key', body="Base is promised. Bonus is hoped. Anything not in the letter isn't real yet."),
        dict(kind='check',
             question='Your offer says $60,000 base with a 10% target bonus. What can you count on?',
             choices=['$60,000, plus the bonus if goals are hit', '$66,000, since the target is in writing', '$60,000, plus a smaller guaranteed bonus'],
             answer=0,
             why="Target means conditional on the company's year and on yours, so you budget on the base and treat a paid bonus as extra."),
    ])
