LESSON = dict(
    id="work-4", track="work", minutes=3,
    title="How to read an offer letter",
    blurb="An offer letter has five parts, and most people read one. Here's what each line means, which number is real, and what to ask for before you sign.",
    takeaway="You learned to read an offer for what is promised, what is hoped, and what is missing.",
    cards=[
        dict(kind="image", src="p01-inbox", eyebrow="The moment",
             body="The offer lands in your inbox. You read it once, fast, hunting for the number. Then you want to sign tonight before it disappears. Slow down. There are five parts, and the salary is only one.",
             paint="A college student at a kitchen table in the evening, laptop open, one hand over their mouth, eyes wide, a happy shocked grin. The laptop screen shows only a soft white page with one big green button and a few grey bars (no words). A phone face down beside it. Exactly one person. The card says: the offer lands and you want to sign it tonight. Slow down."),
        dict(kind="image", src="fig-02-five-parts", eyebrow="What it is",
             body="An offer letter is the company's written promise of a job. It lists what you get and when you start. If something is not in the letter, it is not promised. Not yet."),
        dict(kind="image", src="fig-03-base", eyebrow="The real number",
             body="Base salary is the only number you can count on. $60,000 a year is $5,000 a month before taxes. After taxes, plan on roughly $4,000 landing in your account, depending on your state."),
        dict(kind="image", src="fig-04-bonus", eyebrow="The maybe number",
             body="A 10% target bonus sounds like $6,000. It is not. Target means if the company hits its goals and you hit yours. Some years it pays in full. Some years it pays zero."),
        dict(kind="image", src="p05-hallway", eyebrow="Said out loud",
             body="In the interview, the manager said you could work from home on Fridays. It is not in the letter. Spoken promises leave when that manager leaves. If it matters to you, it goes in the letter.",
             paint="A bright office hallway. A friendly manager in their forties, mid-sentence, one hand open in a casual promise, talking to a college-age candidate who is nodding and smiling. Glass walls, plants, afternoon light. Exactly two people. No signs, badges or screens with words. The card says: the manager said Fridays from home, but it is not in the letter."),
        dict(kind="image", src="fig-06-ask", eyebrow="Ask in writing",
             body="Asking is normal and nobody minds. One short reply does it. Thank them, name the one thing, and say you will sign once it is added. Keep it warm and keep it short."),
        dict(kind="image", src="p07-deadline", eyebrow="The deadline",
             body="'Please sign by Friday' is standard, not a threat. Asking for a week to think is also standard. Companies expect it. A place that pulls the offer because you asked has told you something useful.",
             paint="A college-age person sitting calmly on a dorm bed by a window, phone to their ear, relaxed posture, a small confident smile, a notebook open on their knee with a few squiggled lines. Soft morning light. Exactly one person. No words on the notebook, nothing on the phone screen. The card says: asking for a week to think is standard, and companies expect it."),
        dict(kind="image", src="fig-08-contingent", eyebrow="The small print",
             body="Most offers are contingent. That means the job is real once a few checks clear. A background check, proof of your degree, sometimes a drug test. Until they clear, do not quit anything."),
        dict(kind="image", src="p09-sign", eyebrow="Then sign",
             body="Now you know what is promised, what is hoped, and what is missing. Reply with the signed letter and your start date in one line. Keep a copy. You will want it at your first review.",
             paint="Close view of a tidy desk from above: a person's hand signing the bottom of a printed letter with a pen, the letter's text shown only as soft grey squiggled lines, a mug of coffee, a plant, warm lamplight. No face visible, one hand only. No real letters or numbers anywhere on the page. The card says: sign it, send it with your start date, and keep a copy."),
        dict(kind="key", body="Base is promised. Bonus is hoped. Anything not in the letter is not yet real."),
        dict(kind="check",
             question="Your offer says $60,000 base with a 10% target bonus. What can you count on?",
             choices=["$60,000, plus the bonus if goals are hit",
                      "$66,000, since the target is in writing",
                      "$60,000, plus a smaller guaranteed bonus"],
             answer=0,
             why="Target means conditional. The bonus depends on the company's year and on yours. Budget on the base and treat a paid bonus as a good surprise."),
    ])
