LESSON = dict(
    id='work-12', track='work', minutes=3,
    title="What 'benefits' actually means",
    blurb="Two offers, and the lower salary can pay more. You'll see what the four insurance words mean, what fifteen days off and a 4% match are worth in dollars, and the one line that compares two jobs honestly.",
    takeaway='Price the benefits, then compare the one line, not the bold number.',
    cards=[
        dict(kind='image', src='p01-two-offers', eyebrow='Two offers',
             body="Job A pays $60,000 and Job B pays $58,000, so it's easy, right? Not yet. Job A wants $300 a month for health insurance and Job B wants $50. Now B pays more, and that's what 'benefits' means.",
             paint='A college-age person at a kitchen table with two printed letters laid side by side, one hand on each, looking from one to the other with a puzzled frown, a calculator and a mug nearby, evening lamplight. Exactly one person. The letters show only grey squiggled lines and one bold grey bar each, no numbers or words. The card says: Job A pays more on paper, and Job B pays more in truth.'),
        dict(kind='image', src='fig-02-what-they-are', eyebrow='What benefits are',
             body="Benefits are the parts of pay that aren't salary: health insurance, paid days off, a retirement match. They're real money. They're just harder to see than the number in bold, which is why the bold number wins arguments it shouldn't."),
        dict(kind='image', src='fig-03-four-words', eyebrow='Four insurance words',
             body='Premium: what you pay every month no matter what. Deductible: what you pay yourself before insurance starts. Copay: the flat fee per visit. Out-of-pocket max: the most you can pay in a year, and the number that matters if something goes wrong.'),
        dict(kind='image', src='fig-04-compare', eyebrow='The one-line compare',
             body="Salary minus the year's premiums. A: $60,000 minus $3,600 is $56,400. B: $58,000 minus $600 is $57,400. B pays $1,000 more before you've seen a doctor, and the bold number said the opposite."),
        dict(kind='image', src='p05-parents', eyebrow='Under 26',
             body="If you're under 26 you can usually stay on a parent's plan, which the Affordable Care Act guarantees. Then a job's insurance is worth less to you and salary matters more. Ask what it costs your parents to keep you on.",
             paint="A college-age person on a video call at a laptop in a bright living room, the screen showing two parents in their fifties waving and smiling (faces soft, no words), the young person laughing with a notebook open. Exactly three people, two of them on the screen. No words anywhere. The card says: under 26 you can usually stay on a parent's plan, so ask what that costs."),
        dict(kind='image', src='fig-06-pto', eyebrow='Days off are pay',
             body="Paid time off is days you're paid not to work. Job B's fifteen days at $58,000 are about $3,300 of pay for not working, and Job A's ten days about $2,300. Count them, and ask whether unused days roll over."),
        dict(kind='image', src='fig-07-match', eyebrow='The match',
             body="A 401(k) match is free money on top of salary, if you put some in. Job B's 4% match on $58,000 is $2,320 a year. Job A has no match, so it quietly pays $2,320 less, and the bold number never says so."),
        dict(kind='image', src='p08-ask', eyebrow='Ask for the summary',
             body='Every company has a one-page benefits summary. Ask the recruiter for it before you decide, and nobody will mind. Reading it is the difference between choosing a number and choosing a job.',
             paint='A college-age person on the phone by a sunny window, relaxed and friendly, a single printed page in the other hand held up to the light, a plant on the sill. Exactly one person. The page shows only grey lines and a few coloured boxes, no words. The card says: ask the recruiter for the one-page benefits summary before you decide.'),
        dict(kind='image', src='fig-09-total', eyebrow='Total it up',
             body='Put it on one line: salary, minus premiums, plus the match, plus days off. A comes to about $58,700 and B to about $63,100. Two thousand apart on paper, over four thousand apart in truth, and it took five minutes.'),
        dict(kind='key', body='Salary minus premiums, plus the match, plus days off. Compare that line, not the bold number.'),
        dict(kind='check',
             question='Job A: $60,000, $300 a month for insurance. Job B: $58,000, $50 a month. Which pays more?',
             choices=['Job B, by about $1,000 a year after premiums', 'Job A, since $2,000 more salary beats a premium', "They're equal, because premiums come out pre-tax"],
             answer=0,
             why="A's premiums cost $3,600 a year and B's cost $600, and that $3,000 gap is bigger than the $2,000 salary gap."),
    ])
