LESSON = dict(
    id='work-6', track='work', minutes=3,
    title='Feedback is data, not a verdict',
    blurb="Feedback lands like a grade on who you are, and it isn't one. You'll see how to hear it, the three words that stop you defending, and why the useful half only shows up the next morning.",
    takeaway='Feedback is information about the work, not a ruling on you.',
    cards=[
        dict(kind='image', src='p01-review', eyebrow='The sting',
             body="Your manager says the report was hard to follow and your face goes hot. You start explaining. Ten minutes later you can't remember what they said, only that it hurt, and the useful part is already gone.",
             paint='A small glass meeting room. A manager in their thirties speaking calmly across a table, a printed report between them. Opposite, a college-age employee with flushed cheeks, shoulders up, mid-sentence, one hand raised as if explaining. Exactly two people. The report shows only grey squiggled lines, no words. The card says: the report was hard to follow, your face goes hot, you start explaining.'),
        dict(kind='image', src='fig-02-what-it-is', eyebrow='What it is',
             body="Feedback is one person telling you how your work landed for them. It's a data point about the work, not a grade on you. Those two feel identical in the moment, and they aren't."),
        dict(kind='image', src='fig-03-two-parts', eyebrow='Delivery vs content',
             body='Every piece of feedback has two parts: how it was said and what it says. A clumsy delivery can carry a true point. Judge the content and let the delivery go, which is harder than it sounds.'),
        dict(kind='image', src='fig-04-three-words', eyebrow='Three words',
             body="Say 'Thanks, tell me more' and then stop talking. Those three words do two jobs. They stop you defending, and they get you an example, which is the only part of feedback you can actually use."),
        dict(kind='image', src='p05-walk', eyebrow='Twenty-four hours',
             body="Don't decide anything in the room. Sleep on it. Feedback that felt unfair at 3pm often reads as half right by morning, and the half that's right is the useful half. The other half you're allowed to drop.",
             paint='A college-age person walking home alone along a tree-lined street at dusk, hands in jacket pockets, thoughtful but calm, streetlights just coming on, a bag over one shoulder. Exactly one person. No signs, no number plates, no words. The card says: do not decide anything in the room, sleep on it.'),
        dict(kind='image', src='fig-06-sort', eyebrow='Sort it',
             body='Next morning, sort it into three piles: true, do it; true, but not now; not true, let it go. Most feedback has something in the first pile. Almost none of it belongs entirely in the third, however it felt.'),
        dict(kind='image', src='p07-ask', eyebrow='Ask early',
             body="Waiting for the review means feedback arrives too late to use. Ask while the work is half done: 'What's one thing that would make this better?' One thing is easy to give, easy to take, and early enough to fix.",
             paint="A college-age employee standing beside a senior coworker's desk, holding a laptop open toward them, both looking at the screen together, the senior person pointing at one spot with a helpful expression. Bright office, plants. Exactly two people. The screen shows only soft coloured blocks and bars, no words. The card says: ask while the work is half done, what is one thing that would make this better."),
        dict(kind='image', src='fig-08-sandwich', eyebrow='The praise sandwich',
             body="If someone opens with praise, listen for the 'but'. The middle is the message. Nobody has shown the sandwich lands better, and most people hear the 'but' coming, so when you give feedback, say the one thing plainly and kindly."),
        dict(kind='image', src='p09-later', eyebrow='Close the loop',
             body="Two weeks later, go back. 'I tried the shorter version you suggested. Did it read better?' That closes the loop. It also tells them their feedback was worth giving, which is how you get more of it next time.",
             paint='Two weeks later: the same manager and the same college-age employee passing in a bright office corridor, the employee saying something with an easy smile, the manager nodding with a pleased look, coffee cups in hand. Exactly two people. No words anywhere. The card says: two weeks later, go back and close the loop.'),
        dict(kind='key', body="Hear it, thank them, ask for an example, decide tomorrow. It's about the work."),
        dict(kind='check',
             question="Your manager says your report was hard to follow. What's the best first reply?",
             choices=["'Thanks. Which part lost you first, exactly?'", "'I only had a day, and the data was messy.'", "'Okay, I'll rewrite the whole thing tonight.'"],
             answer=0,
             why='Thanking them and asking for the example gets you the one part you can use, while explaining or rewriting everything skips finding out what was actually wrong.'),
    ])
