LESSON = dict(
    id="work-6", track="work", minutes=3,
    title="Feedback is data, not a verdict",
    blurb="Feedback lands like a grade on who you are. It is not. Here's how to hear it, the three words that buy time, and how to ask for it before it hurts.",
    takeaway="You learned to take feedback as information about the work, not a ruling on you.",
    cards=[
        dict(kind="image", src="p01-review", eyebrow="The sting",
             body="Your manager says the report was hard to follow. Your face goes hot. You start explaining. Ten minutes later you cannot remember what they said. Only that it hurt.",
             paint="A small glass meeting room. A manager in their thirties speaking calmly across a table, a printed report between them. Opposite, a college-age employee with flushed cheeks, shoulders up, mid-sentence, one hand raised as if explaining. Exactly two people. The report shows only grey squiggled lines, no words. The card says: the report was hard to follow, your face goes hot, you start explaining."),
        dict(kind="image", src="fig-02-what-it-is", eyebrow="What it is",
             body="Feedback is someone telling you how your work landed for them. It is a data point about the work. It is not a grade on you. Those feel the same in the moment. They are not."),
        dict(kind="image", src="fig-03-two-parts", eyebrow="Delivery vs content",
             body="Every piece of feedback has two parts. How it was said, and what it says. A clumsy delivery can carry a true point. Judge the content. Let the delivery go."),
        dict(kind="image", src="fig-04-three-words", eyebrow="Three words",
             body="Say 'Thanks, tell me more.' Then stop. Those three words do two jobs. They stop you defending. And they get you an example, which is the only part you can actually use."),
        dict(kind="image", src="p05-walk", eyebrow="Twenty-four hours",
             body="Do not decide anything in the room. Sleep on it. Feedback that felt unfair at 3pm often reads as half right by morning. The half that is right is the useful half.",
             paint="A college-age person walking home alone along a tree-lined street at dusk, hands in jacket pockets, thoughtful but calm, streetlights just coming on, a bag over one shoulder. Exactly one person. No signs, no number plates, no words. The card says: do not decide anything in the room, sleep on it."),
        dict(kind="image", src="fig-06-sort", eyebrow="Sort it",
             body="Next morning, sort it into three piles. True, do it. True, but not now. Not true, let it go. Most feedback has something in the first pile. Almost none is all in the third."),
        dict(kind="image", src="p07-ask", eyebrow="Ask early",
             body="Waiting for the review means feedback arrives too late to use. Ask while the work is half done. 'What's one thing that would make this better?' One thing is easy to give and easy to take.",
             paint="A college-age employee standing beside a senior coworker's desk, holding a laptop open toward them, both looking at the screen together, the senior person pointing at one spot with a helpful expression. Bright office, plants. Exactly two people. The screen shows only soft coloured blocks and bars, no words. The card says: ask while the work is half done, what is one thing that would make this better."),
        dict(kind="image", src="fig-08-sandwich", eyebrow="The praise sandwich",
             body="If someone opens with praise, listen for the 'but'. The middle is the message. And when you give feedback, skip the sandwich. Say the one thing, kindly and plainly."),
        dict(kind="image", src="p09-later", eyebrow="Close the loop",
             body="Two weeks later, go back. 'I tried the shorter version you suggested. Did it read better?' That closes the loop. It tells them their feedback was worth giving, so you get more of it.",
             paint="Two weeks later: the same manager and the same college-age employee passing in a bright office corridor, the employee saying something with an easy smile, the manager nodding with a pleased look, coffee cups in hand. Exactly two people. No words anywhere. The card says: two weeks later, go back and close the loop."),
        dict(kind="key", body="Hear it, thank them, ask for an example, decide tomorrow. Feedback is about the work."),
        dict(kind="check",
             question="Your manager says your report was hard to follow. What's the best first reply?",
             choices=["'Thanks. Which part lost you first, exactly?'",
                      "'I only had a day, and the data was messy.'",
                      "'Okay, I'll rewrite the whole thing tonight.'"],
             answer=0,
             why="It thanks them and asks for the example, which is the part you can use. Explaining is defending, and rewriting everything skips finding out what was actually wrong."),
    ])
