import SwiftUI

// Generated by design/icons/pack.py. Do not edit — change the icon's tint in
// design/icons/icons.py and rerun, so the tile and the object cannot disagree.

/// The six tile tints. An icon does not get to invent a seventh: a tile takes the
/// hue family of the object standing in it, and there are six families.
enum IconTint: String {
    case sky, gold, mint, coral, lilac, indigo

    /// The tile fill.
    var soft: Color {
        switch self {
        case .sky: return Theme.hex(0xE3EEFB)
        case .gold: return Theme.hex(0xFCEFD3)
        case .mint: return Theme.hex(0xDFF3E9)
        case .coral: return Theme.hex(0xFFE9E5)
        case .lilac: return Theme.hex(0xEDE7FB)
        case .indigo: return Theme.hex(0xE7E7F6)
        }
    }

    /// Which tint an icon's tile takes. An unknown name lands on sky rather than
    /// crashing, so a task category added before its art still draws a tile.
    static func of(_ icon: String) -> IconTint {
        switch icon {
        case "problemSet", "lifeCare", "connect", "psychology", "tabLearn", "tabPlay": return .sky
        case "writing", "tidy", "finance", "star", "tabFocus", "snack": return .gold
        case "labs", "walk", "outdoors", "studyTrack", "highFive": return .mint
        case "reading", "meal", "people", "calculator", "heart", "tabHome", "tabFriends", "pet": return .coral
        case "study", "stretch", "philosophy", "tabCalendar", "collection": return .lilac
        case "sleep", "work": return .indigo
        default: return .sky
        }
    }
}

/// One icon on its tile. The only way the app draws a content icon.
///
/// 44 in a row, 52 on a card. The corner is a constant fraction of the side, so
/// both land on the radius scale without a second rule.
struct IconTile: View {
    let icon: String
    var size: CGFloat = 44

    var body: some View {
        RoundedRectangle(cornerRadius: Theme.Radius.tile(size), style: .continuous)
            .fill(IconTint.of(icon).soft)
            .frame(width: size, height: size)
            .overlay(
                Image("icon-" + icon)
                    .resizable()
                    .scaledToFit()
                    .frame(width: size * 0.72, height: size * 0.72)
            )
            .accessibilityHidden(true)
    }
}
