#!/usr/bin/env bash
# Copies bridge/config.local.json into the two places that need it:
# the Chrome extension and the iOS app bundle. Both outputs are gitignored,
# so the keys never land in a commit.
#
# Run this once after editing config.local.json, and again if you rotate a key.
set -euo pipefail
cd "$(dirname "$0")/.."

SRC=bridge/config.local.json
[ -f "$SRC" ] || { echo "missing $SRC — copy bridge/config.example.json and fill it in"; exit 1; }

python3 - "$SRC" <<'PY'
import json, sys, pathlib
c = json.load(open(sys.argv[1]))
url, key = c.get("url", "").rstrip("/"), c.get("publishableKey", "")
if not url or not key:
    sys.exit("config.local.json still has an empty url or publishableKey")

pathlib.Path("extension/config.js").write_text(
    "// Generated by bridge/apply-config.sh. Do not edit, do not commit.\n"
    f"const PREPKIN_BRIDGE = {json.dumps({'url': url, 'key': key}, indent=2)};\n")

pathlib.Path("ios/Resources/bridge-config.json").write_text(
    json.dumps({"url": url, "publishableKey": key}, indent=2) + "\n")

print(f"wrote extension/config.js and ios/Resources/bridge-config.json for {url}")
PY
