#!/usr/bin/env python3
"""Ports the traced slime from SlimeView.swift into SVG paths for the extension.

The app's art is normalised cubic Beziers in a 0..1 box, which is exactly what an
SVG path needs, so this is a lossless copy rather than a redraw. Run it again if
the traced art changes; never hand-edit the generated file.
"""
import re, json, pathlib, sys

SRC = pathlib.Path("ios/Sources/SlimeView.swift")
OUT = pathlib.Path("extension/slime.js")
# Only the traced arrays. faceSleep/Surprised/Sad/Focused/Wink are built at
# runtime from arcStroke/ellipseSub helpers, so there is no literal data to copy
# and inventing one here would put a second, drifting slime in the world.
WANT = ["body", "belly", "faceIdle", "faceDeadpan", "faceJudging", "faceDelight"]

text = SRC.read_text()

def grab(name):
    """Pull one `static let <name>: [[[Double]]] = [ ... ]` block."""
    # Start looking after the `=`, or the type annotation's own brackets get
    # matched instead of the data.
    start = text.index(f"static let {name}: [[[Double]]] =")
    i = text.index("[", text.index("=", start))
    depth, j = 0, i
    while True:
        if text[j] == "[": depth += 1
        elif text[j] == "]":
            depth -= 1
            if depth == 0: break
        j += 1
    body = text[i:j + 1]
    nums = [float(n) for n in re.findall(r"-?\d+\.?\d*", body)]
    if not nums or len(nums) % 8:
        sys.exit(f"{name}: {len(nums)} numbers is not whole 8-value segments — "
                 "is it built from helpers rather than traced?")
    segs = [nums[k:k + 8] for k in range(0, len(nums), 8)]
    # Segments are contiguous within a subpath: each one starts where the last
    # ended. A jump means a new subpath.
    subpaths, current = [], [segs[0]]
    for prev, seg in zip(segs, segs[1:]):
        if (round(prev[6], 4), round(prev[7], 4)) == (round(seg[0], 4), round(seg[1], 4)):
            current.append(seg)
        else:
            subpaths.append(current); current = [seg]
    subpaths.append(current)
    return subpaths

def to_path(subpaths):
    out = []
    for segs in subpaths:
        f = lambda v: f"{v:.4f}".rstrip("0").rstrip(".")
        out.append(f"M{f(segs[0][0])} {f(segs[0][1])}")
        for s in segs:
            out.append(f"C{f(s[2])} {f(s[3])} {f(s[4])} {f(s[5])} {f(s[6])} {f(s[7])}")
        out.append("Z")
    return "".join(out)

paths = {name: to_path(grab(name)) for name in WANT}
# faceWink is built in Swift from pieces of two other faces.
aspect = float(re.search(r"static let aspect: CGFloat = ([\d.]+)", text).group(1))

OUT.write_text(
    "// GENERATED by bridge/port-slime.py from ios/Sources/SlimeView.swift.\n"
    "// The same traced art the app draws, so the two slimes cannot drift apart.\n"
    "// Do not hand-edit. Re-run the script instead.\n"
    f"const SLIME_ASPECT = {aspect};\n"
    f"const SLIME_PALETTE = {json.dumps({'body': '#51CFA0', 'belly': '#B1EDD4', 'ink': '#101820', 'blush': '#FF9E94'}, indent=2)};\n"
    f"const SLIME_PATHS = {json.dumps(paths, indent=2)};\n"
    "\nif (typeof module !== 'undefined') module.exports = { SLIME_PATHS, SLIME_PALETTE, SLIME_ASPECT };\n"
)
print(f"wrote {OUT} — {', '.join(f'{k}:{len(v)}ch' for k, v in paths.items())}")
