import EventKit
import Foundation

/// Dated work, sent out to the calendar the student already uses.
///
/// Two ways out, and no third: **Apple Calendar** through EventKit, and a **file**
/// any other calendar can open, including Google's. There is no Google account and
/// no server in either path (`PLUS-SPEC.md` signature 5) — a file import gets a
/// student into Google Calendar without Prepkin ever asking them to sign in to
/// anything, which is the whole reason that signature was recommended against.
///
/// Write-only access, on purpose. `EKEventStore.requestWriteOnlyAccessToEvents` asks
/// for permission to add events and *not* to read the calendar, which is both the
/// smaller ask and the true one: nothing in Prepkin ever reads what is already in a
/// student's calendar.
enum CalendarExport {

    /// A dated task, as an event. Pure, so the mapping is testable without a store.
    struct Plan: Equatable {
        var title: String
        var notes: String?
        var start: Date
        var end: Date
        var isAllDay: Bool
        /// Stable per task, so re-sending an already-sent task can be recognised
        /// rather than duplicated.
        var key: String
    }

    /// An hour, for a task with a time on it. A task with no time is an all-day
    /// event rather than an event at midnight, because midnight is a lie about when
    /// the work happens.
    static let defaultDuration: TimeInterval = 60 * 60

    static func plan(
        _ task: DatedTask,
        calendar: Calendar = .current
    ) -> Plan? {
        // `DayKey.date` is the app's own answer for "midnight on this day", and
        // reusing it is what keeps an exported event on the same day the row is on.
        guard let midnight = task.day.date(calendar: calendar) else { return nil }

        let notes = [task.detail, task.notes]
            .compactMap { $0 }
            .filter { !$0.isEmpty }
            .joined(separator: "\n")

        guard let minute = task.minute else {
            return Plan(
                title: task.title,
                notes: notes.isEmpty ? nil : notes,
                start: midnight,
                end: midnight,
                isAllDay: true,
                key: "prepkin-\(task.id)"
            )
        }
        let start = midnight.addingTimeInterval(TimeInterval(minute) * 60)
        return Plan(
            title: task.title,
            notes: notes.isEmpty ? nil : notes,
            start: start,
            end: start.addingTimeInterval(defaultDuration),
            isAllDay: false,
            key: "prepkin-\(task.id)"
        )
    }

    // MARK: - Apple Calendar

    enum Failure: Error, Equatable {
        case notAllowed
        case noCalendar
        case failed
    }

    /// Asks once, then writes. Returns how many events landed.
    ///
    /// A refusal is not an error the student has to dismiss — the caller says
    /// "Prepkin can't add to your calendar yet" and points at Settings, because a
    /// permission sheet that has already been answered will not come back.
    @discardableResult
    static func send(_ tasks: [DatedTask], to store: EKEventStore = EKEventStore()) async throws -> Int {
        let allowed = try await store.requestWriteOnlyAccessToEvents()
        guard allowed else { throw Failure.notAllowed }
        guard let target = store.defaultCalendarForNewEvents else { throw Failure.noCalendar }

        var written = 0
        for task in tasks {
            guard let plan = plan(task) else { continue }
            let event = EKEvent(eventStore: store)
            event.title = plan.title
            event.notes = plan.notes
            event.startDate = plan.start
            event.endDate = plan.end
            event.isAllDay = plan.isAllDay
            event.calendar = target
            do {
                try store.save(event, span: .thisEvent, commit: false)
                written += 1
            } catch {
                continue
            }
        }
        do {
            try store.commit()
        } catch {
            throw Failure.failed
        }
        return written
    }

    // MARK: - A file, for everything else

    /// One calendar file holding every dated task. Google, Outlook and Fantastical
    /// all import this, so "your own calendar" does not mean "an Apple calendar".
    ///
    /// Hand-built rather than generated by a library: the format is nine lines and a
    /// dependency for it would be a dependency to audit.
    static func file(_ tasks: [DatedTask], now: Date = Date()) -> String {
        var out = [
            "BEGIN:VCALENDAR",
            "VERSION:2.0",
            "PRODID:-//Prepkin//Prepkin for Canvas//EN",
            "CALSCALE:GREGORIAN",
        ]
        for task in tasks {
            guard let plan = plan(task) else { continue }
            out.append("BEGIN:VEVENT")
            out.append("UID:\(plan.key)@prepkin.com")
            out.append("DTSTAMP:\(utc(now))")
            if plan.isAllDay {
                out.append("DTSTART;VALUE=DATE:\(dateOnly(plan.start))")
                out.append("DTEND;VALUE=DATE:\(dateOnly(plan.end.addingTimeInterval(86_400)))")
            } else {
                out.append("DTSTART:\(utc(plan.start))")
                out.append("DTEND:\(utc(plan.end))")
            }
            out.append("SUMMARY:\(escape(plan.title))")
            if let notes = plan.notes {
                out.append("DESCRIPTION:\(escape(notes))")
            }
            out.append("END:VEVENT")
        }
        out.append("END:VCALENDAR")
        // RFC 5545 wants CRLF, and Outlook is the one that actually minds.
        return out.joined(separator: "\r\n") + "\r\n"
    }

    /// Commas, semicolons, backslashes and newlines all have meaning in a calendar
    /// file. A course called "Bio 101; Lab" breaks the line without this.
    static func escape(_ s: String) -> String {
        s.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: ";", with: "\\;")
            .replacingOccurrences(of: ",", with: "\\,")
            .replacingOccurrences(of: "\n", with: "\\n")
    }

    static func utc(_ date: Date) -> String {
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.timeZone = TimeZone(secondsFromGMT: 0)
        f.dateFormat = "yyyyMMdd'T'HHmmss'Z'"
        return f.string(from: date)
    }

    static func dateOnly(_ date: Date, calendar: Calendar = .current) -> String {
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.calendar = calendar
        f.timeZone = calendar.timeZone
        f.dateFormat = "yyyyMMdd"
        return f.string(from: date)
    }

    /// Writes the file somewhere the share sheet can reach it.
    static func writeFile(_ tasks: [DatedTask], named name: String = "Prepkin.ics") throws -> URL {
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(name)
        try file(tasks).write(to: url, atomically: true, encoding: .utf8)
        return url
    }
}
