import Foundation

/// The swim: Finch's adventure without the energy bar.
///
/// Finish the list and the fish leaves the tank. It comes back at the student's
/// check-in hour with a find. That is the whole mechanic. The list is the bar,
/// so nothing here is a meter; a day the list is not finished the fish stays
/// home and nothing else happens; "back at 7 PM" is a time, not a countdown.
/// Neko Atsume's rule holds too: the reward is generated by absence, and there
/// is no fail state.
struct Swim: Codable, Equatable {
    let day: DayKey
    let startedAt: Date
    let returnsAt: Date
    /// Drawn when the swim starts, so the widget can say what was found at the
    /// hour without the app running. Paid and kept when the app next opens.
    let findID: String
    var collected = false

    func isAway(at now: Date) -> Bool { now < returnsAt }
    /// Back, and the app has not yet paid the find.
    func isBack(at now: Date) -> Bool { now >= returnsAt && !collected }

    var find: Find { Find.named(findID) }

    /// What a find pays. Coins, so the ledger stays the one reward.
    static let coins = 10

    /// The fish is back at the check-in hour. If the list was finished after
    /// that hour, or too close to it, it is back in two hours instead.
    static func returnTime(after now: Date, checkInHour: Int, calendar: Calendar = .current) -> Date {
        let soonest = now.addingTimeInterval(30 * 60)
        if let atHour = calendar.date(bySettingHour: checkInHour, minute: 0, second: 0, of: now), atHour >= soonest {
            return atHour
        }
        return now.addingTimeInterval(2 * 3600)
    }
}

/// What the fish brings back. A small pool to start; each is a line on the
/// kin's card, and stands in the tank once Decorate is on and its art lands.
struct Find: Identifiable, Equatable {
    let id: String
    /// With its article, for a sentence: "found a shell".
    let name: String

    static let pool: [Find] = [
        Find(id: "shell", name: "a shell"),
        Find(id: "pebble", name: "a smooth pebble"),
        Find(id: "sea-glass", name: "sea glass"),
        Find(id: "bottle-cap", name: "a bottle cap"),
        Find(id: "feather", name: "a feather"),
        Find(id: "coin", name: "an old coin"),
        Find(id: "key", name: "a small key"),
        Find(id: "pearl", name: "a pearl"),
    ]

    static func named(_ id: String) -> Find {
        pool.first { $0.id == id } ?? pool[0]
    }

    /// The day's find, by the day and a per-phone seed: the same all day, and the
    /// widget and the app agree without talking.
    static func draw(day: DayKey, seed: Int) -> Find {
        let n = DayBank.dayNumber(raw: day.raw)
        return pool[((n + seed) % pool.count + pool.count) % pool.count]
    }
}

/// A find, kept. One line on the kin's card: "Found a shell · 12 Sep".
struct KinFind: Codable, Equatable, Identifiable {
    let findID: String
    let kinID: String
    let day: DayKey
    let at: Date

    var id: String { "\(kinID):\(day.raw)" }
    var find: Find { Find.named(findID) }
}
