LESSON = dict(
    id="psy-12", track="psychology", minutes=3,
    title="Everything takes twice as long",
    blurb="Students said their thesis would take 34 days. It took 56. Here's the planning fallacy, why it never goes away, and the two fixes that actually work.",
    takeaway="You learned to plan from your past, not from your hopes.",
    cards=[
        dict(kind="image", src="p01-late-night", eyebrow="The night before",
             body="The essay was going to take a weekend. It is Sunday at 11pm and you are on page two. This is not a character flaw. It is a bias with a name, and it has been measured.",
             paint="A college student at a desk late on a Sunday night, hunched over a laptop, hands in hair, the screen showing only a mostly empty page with a short grey block of text, a cold pizza box and an empty mug, dark window. Exactly one person. No words on the screen or box, no clock numbers. The card says: it was going to take a weekend, and it is Sunday at 11pm on page two."),
        dict(kind="image", src="fig-02-what-it-is", eyebrow="What it is",
             body="The planning fallacy is the habit of guessing tasks will take less time than they do. Everyone has it. Knowing about it does not cure it. Only a different way of guessing does."),
        dict(kind="image", src="fig-03-study", eyebrow="The study",
             body="In 1994, students were asked when they would finish their thesis. Average guess: 34 days. Average reality: 56 days. Fewer than a third finished by the day they had said."),
        dict(kind="image", src="fig-04-why", eyebrow="Why it happens",
             body="When you plan, you imagine the task going well. Nothing else comes up. That is the inside view. But something always comes up. You just cannot say what yet."),
        dict(kind="image", src="p05-remember", eyebrow="The outside view",
             body="Stop imagining the task. Remember the last one. How long did the last essay take? Not the plan, the real time. That number is the best forecast you have.",
             paint="A college student sitting on a dorm bed flipping back through an old paper planner, one finger on a page, eyebrows raised at what they find, afternoon light, a backpack on the floor. Exactly one person. The planner shows only squiggles and coloured blocks, no words or numbers. The card says: stop imagining the task and remember how long the last one really took."),
        dict(kind="image", src="fig-06-multiply", eyebrow="Multiply",
             body="The students were off by a factor of about 1.6. If you have no record, take your guess and multiply by 1.5. A weekend becomes three days. Uncomfortable, and usually right."),
        dict(kind="image", src="fig-07-parts", eyebrow="Break it into parts",
             body="Guess the parts, not the whole. Reading, two hours. Outline, one. Draft, four. Edits, two. The parts add up bigger than the single guess, and closer to the truth."),
        dict(kind="image", src="p08-buffer", eyebrow="The buffer",
             body="Put the finish date two days before the real one. Then treat the fake date as real. If nothing goes wrong, you finish early. Something goes wrong.",
             paint="A college student pinning a small paper calendar page to a corkboard above a desk, a red sticker dot placed a couple of squares before a circled square, a satisfied nod, morning light. Exactly one person. The calendar is a plain grid with no numbers or letters. The card says: put the finish date two days early, then treat the fake date as real."),
        dict(kind="image", src="p09-record", eyebrow="Keep the record",
             body="After each big task, write down what you guessed and what it took. Two numbers. In a semester you will know your own factor. That number beats every productivity tip.",
             paint="Close view of a college student's hands writing a short entry in a small notebook at a cafe table, two short columns of squiggled marks side by side down the page, a coffee and a laptop closed beside it, warm light. One person's hands only, no face. No real words or numbers on the page. The card says: after each big task, write down the guess and the real time."),
        dict(kind="key", body="Guess from the last time, not from the plan. No record? Multiply by 1.5 and split it into parts."),
        dict(kind="check",
             question="You think the lab report will take three hours. The last one took five. What do you plan for?",
             choices=["Five hours, because last time is the best forecast",
                      "Three hours, because you know the format by now",
                      "Four hours, splitting the difference to be fair"],
             answer=0,
             why="The outside view beats the inside view. Last time already includes the things that came up, and things always come up."),
    ])
