LESSON = dict(
    id="work-5", track="work", minutes=3,
    title="Your first week: write everything down",
    blurb="Nobody expects output in week one. They expect questions and a notebook. Here's what to write down, who to ask, and the one question for your manager.",
    takeaway="You learned that week one is for collecting, not proving.",
    cards=[
        dict(kind="image", src="p01-desk", eyebrow="Day one",
             body="You get a laptop, a badge, and a wall of names. By lunch you have met twelve people and remember three. Nobody minds. Week one is not a test. It is a collection.",
             paint="A new employee, college-age, standing a little lost in a bright open-plan office on their first morning, holding a closed laptop against their chest and a lanyard with a blank badge. Around them, a few coworkers at desks glance up with friendly faces. Exactly four people. No words on screens, badges, or walls. The card says: day one, a laptop, a badge, and a wall of names."),
        dict(kind="image", src="fig-02-what-it-is", eyebrow="What it is",
             body="Onboarding is the company's word for learning how it works. Nobody expects work from you yet. They expect you to ask, watch, and write. That is the whole job for now."),
        dict(kind="image", src="fig-03-four-lists", eyebrow="Four lists",
             body="Keep four lists from the first hour. Names, and what each person owns. Words and acronyms you did not know. Where things live. Questions you have not asked yet."),
        dict(kind="image", src="p04-question", eyebrow="Questions are free",
             body="Every question is free in the first month. 'What does that acronym mean?' costs nothing in week one. In month three the same question costs a little pride. Spend the free ones.",
             paint="A college-age new hire leaning over to a coworker at the next desk, asking something with an open, unembarrassed face, the coworker turning with a warm smile to answer. Bright office, plants, afternoon light. Exactly two people. Screens show only soft blurs, no words. The card says: every question is free in the first month, so spend the free ones."),
        dict(kind="image", src="fig-05-price", eyebrow="The price goes up",
             body="It is not that people get meaner. It is that they start assuming you know. So the sooner you ask, the cheaper it is. The dumbest question is the one you finally ask in month six."),
        dict(kind="image", src="fig-06-one-question", eyebrow="The one question",
             body="In your first one to one, ask this. 'What does good look like at ninety days?' Write the answer down word for word. That sentence is your real job description for three months."),
        dict(kind="image", src="p07-shadow", eyebrow="Watch how it's done",
             body="Ask to sit in on something. A call, a review, a meeting you were not invited to. Say you want to see how it works. People like showing. The unwritten rules live there.",
             paint="A small meeting room seen from the doorway: three coworkers around a table mid-discussion, and a college-age new hire sitting slightly back from the table with a notebook, watching and listening intently. Warm light, a whiteboard behind with only coloured squiggles and boxes, no letters. Exactly four people. The card says: ask to sit in on something and watch how it is done."),
        dict(kind="image", src="fig-08-names", eyebrow="The name trick",
             body="By Friday most of the names are gone, unless you wrote each one down with one fact. 'Priya, runs the Tuesday report, has a dog.' The fact is the hook the name hangs on."),
        dict(kind="image", src="p09-friday", eyebrow="Friday",
             body="On Friday, read the four lists back. Ask the three questions still open. Send your manager two lines: what you learned, what you will pick up Monday. That is a good first week.",
             paint="Late Friday afternoon, a college-age employee alone at a tidy desk, reading back through a small notebook with a satisfied half-smile, the office emptying out behind them, low golden light through the windows, a jacket on the chair. Exactly one person. Squiggles only in the notebook, no words. The card says: on Friday, read the four lists back and send two lines."),
        dict(kind="key", body="Week one is for collecting. Names, words, places, questions. Ask while asking is free."),
        dict(kind="check",
             question="It's day three and you still don't know what an acronym in every meeting means. What do you do?",
             choices=["Ask the next person who says it, today",
                      "Look it up quietly so nobody notices",
                      "Wait until you know the team better"],
             answer=0,
             why="Asking is cheapest now and pricier every month. Looking it up works for words, but people also tell you who owns what, and no search finds that."),
    ])
