LESSON = dict(
    id="hlth-5", track="health", minutes=3,
    title="When to actually see a doctor",
    blurb="Most students wait too long or go to the wrong place. Here's what the campus clinic is for, the signs that mean today, the ones that mean the ER, and costs.",
    takeaway="You learned which symptoms wait, which mean today, and which mean the ER.",
    cards=[
        dict(kind="image", src="p01-day-four", eyebrow="Day four",
             body="Day four of the fever. You have missed two classes, googled it twice, and told yourself it is fine. It might be. Here is how to know, without the googling.",
             paint="A college student wrapped in a blanket on a dorm bed in daylight, flushed and tired, holding a phone loosely, a box of tissues, a mug and a thermometer on the nightstand, curtains half drawn. Exactly one person. No words or numbers on the phone or thermometer. The card says: day four of the fever, googled it twice, told yourself it is fine."),
        dict(kind="image", src="fig-02-three-doors", eyebrow="Three doors",
             body="The campus clinic, for most things. Urgent care, when the clinic is closed. The ER, for emergencies only. Same problem, three prices, three waits. Picking right is the whole skill."),
        dict(kind="image", src="fig-03-wait", eyebrow="What can wait a few days",
             body="A cold, a cough without fever, a sore throat with a cough, a stomach bug under a day. Rest, fluids, and time. See someone if it is still there after a week, or gets worse."),
        dict(kind="image", src="fig-04-today", eyebrow="What means today",
             body="A fever over 103°F, or any fever past three days. A sore throat with fever and no cough, which can be strep. An ear that hurts and leaks. Pain when you pee. Book the clinic today."),
        dict(kind="image", src="fig-05-er", eyebrow="What means the ER, now",
             body="Chest pain. Trouble breathing. The worst headache of your life. Fainting. A stiff neck with a fever. Cannot keep water down for a day. Thoughts of ending your life: call or text 988."),
        dict(kind="image", src="p06-clinic", eyebrow="The campus clinic",
             body="Most schools have a clinic you already paid for in your fees. Visits are often free or under $25. Nurses answer the phone. Use it for the boring stuff. That is what it is for.",
             paint="A bright, small campus health clinic waiting room, a college student checking in at a counter with a friendly nurse in scrubs, two chairs and a plant, a poster on the wall that is only coloured shapes. Exactly two people. No words on posters, badges, or screens. The card says: the campus clinic is already paid for, use it for the boring stuff."),
        dict(kind="image", src="fig-07-cost", eyebrow="What each costs",
             body="A typical campus clinic visit: $0 to $25. Urgent care: around $150 to $250. The ER for the same sore throat: often over $1,000. The ER is for when the price does not matter."),
        dict(kind="image", src="p08-call", eyebrow="Call first",
             body="Not sure which door? Call the clinic's nurse line or your insurance's nurse line. Free, and they tell you where to go. Two minutes on the phone can save a four-hour wait.",
             paint="A college student sitting on the edge of a bed, phone to ear, listening carefully and nodding, a notepad on their knee with a couple of squiggles, morning light, a water bottle nearby. Exactly one person. No words on the notepad or phone. The card says: not sure which door, call the nurse line first."),
        dict(kind="image", src="p09-friend", eyebrow="For a friend",
             body="If a friend cannot stay awake, cannot breathe right, or has taken too much of anything, call 911. Do not wait for them to agree. Most schools will not punish the caller. Ask yours.",
             paint="A dorm room at night, one college student kneeling beside a friend who is slumped against the bed, the kneeling student on the phone with a calm, urgent face, one hand on the friend's shoulder, a lamp on. Exactly two people. The slumped friend is drawn as an ordinary lit person, not a silhouette. No words anywhere. The card says: if a friend cannot stay awake or breathe right, call 911 and do not wait for them to agree."),
        dict(kind="key", body="Clinic for most things. Today for fever over 103°F or past three days. ER for chest, breath, head, fainting."),
        dict(kind="check",
             question="Sore throat, fever of 101°F, no cough, day two. Where do you go?",
             choices=["The campus clinic today, it could be strep",
                      "The ER tonight, in case it gets any worse",
                      "Nowhere yet, wait a week and see if it clears"],
             answer=0,
             why="Fever plus a sore throat with no cough is the strep pattern, and strep needs a test and antibiotics. It is not an emergency, and waiting a week risks spreading it."),
    ])
