LESSON = dict(
    id='hlth-7', track='health', minutes=3,
    title="It's the scrolling, not the blue light",
    blurb="Everyone blames the blue light, and the Harvard study puts it at about ten minutes. You'll see what actually costs an hour, why the feed is built that way, and the fix that isn't a filter.",
    takeaway='The phone keeps you up by being interesting, not by being blue.',
    cards=[
        dict(kind='image', src='p01-one-more', eyebrow='One more',
             body="In bed at 11, one more video, and it's 12:40. You turn on the orange filter every night and it doesn't help. That's because the light was never the main problem, and the studies have known for a while.",
             paint='A dark dorm room, a college student lying on their side in bed, face lit warm orange by a phone held close, eyes wide and tired, blanket pulled up, the rest of the room in shadow. Exactly one person. The phone screen is only a soft glow, no words or icons. The card says: in bed at 11, one more video, and it is 12:40.'),
        dict(kind='image', src='fig-02-what-it-is', eyebrow='What the light does',
             body="Blue-ish light tells your body clock it's daytime and delays melatonin, the hormone that says sleep. That's real. The question is how big the effect is, and it's been measured more than once."),
        dict(kind='image', src='fig-03-study', eyebrow='Ten minutes',
             body='In a 2015 Harvard study, Anne-Marie Chang had people read on a bright tablet for four hours before bed. They fell asleep about ten minutes later than with a paper book. Ten minutes, at full brightness, for four hours, five nights running.'),
        dict(kind='image', src='fig-04-night-mode', eyebrow='Night mode',
             body='Later studies tested the orange filter, including a 2021 trial at Brigham Young. Night mode made no difference to how people slept. The filter fixes a ten-minute problem, badly, and the real problem is measured in hours.'),
        dict(kind='image', src='p05-feed', eyebrow='What the feed does',
             body="The feed has no end, and every swipe is a small maybe. That maybe is what keeps you up. Researchers call it bedtime procrastination, and it isn't about light. It's about stopping, which the feed is built to prevent.",
             paint="Close view of a college student's thumb flicking upward on a phone in the dark, the screen a soft vertical blur of coloured rectangles streaming past like an endless ribbon, no icons or words, the face above lit and slack. Exactly one person, partial. The card says: the feed has no end, and every swipe is a small maybe."),
        dict(kind='image', src='fig-06-hours', eyebrow='Where the hour goes',
             body="Ten minutes from the light. Sixty to ninety from the scrolling. Then a lighter, shorter sleep because you're wired. The filter can't touch two of those three, however orange you turn it."),
        dict(kind='image', src='fig-07-place', eyebrow='The fix is a place',
             body="Charge the phone outside the bedroom, or across the room, and buy a $10 alarm clock. The rule isn't 'less scrolling', because that rule loses at 11:40. The rule is the phone doesn't sleep where you do."),
        dict(kind='image', src='p08-book', eyebrow='What to do instead',
             body="The last twenty minutes want something with an end: a chapter, a podcast episode with a timer, a boring one. Ends are what the feed doesn't have, so give yourself one, and the catch is the first night feels strange.",
             paint='A cosy dorm bed at night with one warm bedside lamp, a college student propped on pillows reading a paperback, eyelids getting heavy, a small round alarm clock with a plain blank face on the nightstand, no phone in sight. Exactly one person. No words on the book cover or clock. The card says: the last twenty minutes want something with an end.'),
        dict(kind='image', src='p09-week', eyebrow='One week',
             body='Try a week: phone by the door, alarm clock by the bed. Most people get back thirty to sixty minutes a night without trying, which over a week is almost a whole extra night of sleep.',
             paint='Morning in a dorm room, a college student stretching awake in bed with a rested face, sunlight across the blanket, and across the room by the door a phone sitting on a small shelf plugged into its charger. Exactly one person. No words or icons on the phone. The card says: phone by the door for a week, and most people get back thirty to sixty minutes a night.'),
        dict(kind='key', body='The light costs ten minutes. The scrolling costs an hour. Move the phone, not the colour.'),
        dict(kind='check',
             question='You want to fall asleep faster. Which change makes the biggest difference?',
             choices=['Charge the phone outside the bedroom', 'Turn on night mode after 9pm every night', 'Turn the screen brightness all the way down'],
             answer=0,
             why="The light effect is about ten minutes and night mode didn't move it, while the scrolling costs an hour and only distance fixes that."),
    ])
