LESSON = dict(
    id="hlth-7", track="health", minutes=3,
    title="It's the scrolling, not the blue light",
    blurb="Everyone blames the blue light. The studies say it costs about ten minutes. Here's what actually costs an hour, why the feed does that, and the fix that is not a filter.",
    takeaway="You learned that the phone keeps you up by being interesting, not by being blue.",
    cards=[
        dict(kind="image", src="p01-one-more", eyebrow="One more",
             body="In bed at 11. One more video. It is 12:40. You turn on the orange filter every night and it does not help. Because the light was never the main problem.",
             paint="A dark dorm room, a college student lying on their side in bed, face lit warm orange by a phone held close, eyes wide and tired, blanket pulled up, the rest of the room in shadow. Exactly one person. The phone screen is only a soft glow, no words or icons. The card says: in bed at 11, one more video, and it is 12:40."),
        dict(kind="image", src="fig-02-what-it-is", eyebrow="What the light does",
             body="Blue-ish light tells your body clock it is daytime and delays melatonin, the hormone that says sleep. That is real. The question is how big it is. The studies measured it."),
        dict(kind="image", src="fig-03-study", eyebrow="Ten minutes",
             body="In a Harvard study, people read on a bright tablet for four hours before bed. They fell asleep about ten minutes later than with a paper book. Ten minutes, at full brightness, for four hours."),
        dict(kind="image", src="fig-04-night-mode", eyebrow="Night mode",
             body="Later studies tested the orange filter. Night mode made no difference to how people slept. The filter fixes a ten-minute problem, badly. The real problem is measured in hours."),
        dict(kind="image", src="p05-feed", eyebrow="What the feed does",
             body="The feed has no end. Every swipe is a small maybe. That maybe is what keeps you up. It is called bedtime procrastination, and it is not about light. It is about stopping.",
             paint="Close view of a college student's thumb flicking upward on a phone in the dark, the screen a soft vertical blur of coloured rectangles streaming past like an endless ribbon, no icons or words, the face above lit and slack. Exactly one person, partial. The card says: the feed has no end, and every swipe is a small maybe."),
        dict(kind="image", src="fig-06-hours", eyebrow="Where the hour goes",
             body="Ten minutes from the light. Sixty to ninety from the scrolling. Then a lighter, shorter sleep because you are wired. The filter cannot touch two of the three."),
        dict(kind="image", src="fig-07-place", eyebrow="The fix is a place",
             body="Charge the phone outside the bedroom, or across the room. A $10 alarm clock. The rule is not 'less scrolling'. The rule is the phone does not sleep where you do."),
        dict(kind="image", src="p08-book", eyebrow="What to do instead",
             body="The last twenty minutes want something with an end. A chapter. A podcast episode with a timer. A boring one. Ends are what the feed does not have. Give yourself one.",
             paint="A cosy dorm bed at night with one warm bedside lamp, a college student propped on pillows reading a paperback, eyelids getting heavy, a small round alarm clock with a plain blank face on the nightstand, no phone in sight. Exactly one person. No words on the book cover or clock. The card says: the last twenty minutes want something with an end."),
        dict(kind="image", src="p09-week", eyebrow="One week",
             body="Try a week. Phone by the door, alarm clock by the bed. Most people get back thirty to sixty minutes a night without trying to. That is almost a whole night of sleep a week.",
             paint="Morning in a dorm room, a college student stretching awake in bed with a rested face, sunlight across the blanket, and across the room by the door a phone sitting on a small shelf plugged into its charger. Exactly one person. No words or icons on the phone. The card says: phone by the door for a week, and most people get back thirty to sixty minutes a night."),
        dict(kind="key", body="The light costs ten minutes. The scrolling costs an hour. Move the phone, not the colour."),
        dict(kind="check",
             question="You want to fall asleep faster. Which change makes the biggest difference?",
             choices=["Charge the phone outside the bedroom",
                      "Turn on night mode after 9pm every night",
                      "Turn the screen brightness all the way down"],
             answer=0,
             why="The light effect is about ten minutes, and night mode did not move it. The scrolling costs an hour, and the only reliable fix is distance."),
    ])
