LESSON = dict(
    id='hlth-4', track='health', minutes=3,
    title='The ten-minute walk',
    blurb="A short walk beats coffee for the afternoon and beats the desk for ideas. You'll see the 1987 study that put it against a candy bar, the Stanford creativity numbers, and where ten minutes fits in a day.",
    takeaway='Ten minutes, brisk, phone away: two hours of energy and more ideas than the desk.',
    cards=[
        dict(kind='image', src='p01-slump', eyebrow='3pm',
             body="You're reading the same line for the fourth time. The options feel like coffee, a snack, or pushing through. There's a fourth one, and it's been tested head to head against the snack.",
             paint='A college student at a library desk in the afternoon, cheek resting on one hand, eyes glazed over an open textbook, a vending-machine snack bar and a coffee cup beside the book, warm slanting light. Exactly one person. No words on the book, wrapper, or cup. The card says: reading the same line for the fourth time, and there is a fourth option.'),
        dict(kind='image', src='fig-02-what-it-does', eyebrow='What it does',
             body="A brisk ten-minute walk raises your heart rate a little. More blood reaches the brain, and the chemicals that set mood shift. It's small, and it's also fast, free, and measured, which most afternoon fixes aren't."),
        dict(kind='image', src='fig-03-candy', eyebrow='Walk vs candy bar',
             body='In 1987, Robert Thayer gave people either a candy bar or a ten-minute walk. The candy gave energy for an hour, then more tiredness and tension. The walk gave energy for two hours with no crash.'),
        dict(kind='image', src='fig-04-ideas', eyebrow='Ideas',
             body='Stanford researchers tested people on inventing new uses for objects, sitting and then walking. Walking raised creative output by about 60%, and four in five people did better on their feet. The effect lasted a while after sitting back down.'),
        dict(kind='image', src='p05-outside', eyebrow='Outside if you can',
             body='Outdoors adds a little more: daylight, which resets your clock, and a change of scene. But a lap of the building counts. The walk is the thing, and the scenery is a bonus you can skip on a bad day.',
             paint='A college student walking briskly along a tree-lined campus path in bright afternoon light, arms swinging, chin up, a light backpack, dappled shade on the ground, a building behind. Exactly one person. No signs or words. The card says: outdoors adds light and a change of scene, but a lap of the building counts.'),
        dict(kind='image', src='fig-06-when', eyebrow='When it fits',
             body="Three natural slots: after lunch, when the dip hits; before a hard task, for ideas; after studying, to let it settle. Pick one and tie it to something you already do, or it won't survive the second week."),
        dict(kind='image', src='p07-phone', eyebrow='Phone in your pocket',
             body="Leave the phone in your pocket or the walk is scrolling upright. Let the mind wander, because that wandering is where the creativity study got its effect. The catch: the first few minutes feel boring, and that's the point.",
             paint='A college student walking along a river path, hands free, phone tucked in a back pocket, gazing off at the water with a loose, thinking expression, golden light, a bridge in the distance. Exactly one person. No signs or words. The card says: leave the phone in your pocket and let the mind wander.'),
        dict(kind='image', src='fig-08-stack', eyebrow='Stack it',
             body='Ten minutes a day is seventy minutes a week and about two hours of extra energy each afternoon. Walk to the far coffee shop. Take the call standing up. It adds up without a gym or a plan.'),
        dict(kind='image', src='p09-back', eyebrow='Back at the desk',
             body="Come back and read that line again. It reads the first time now. That isn't willpower, it's blood flow, and it'll be there again tomorrow at the same time.",
             paint='The same library desk: the college student back in the chair, cheeks a little flushed from the air, sitting upright and reading the textbook with a clear, alert face, the snack bar pushed aside unopened. Exactly one person. No words on anything. The card says: come back and the line reads the first time now.'),
        dict(kind='key', body='Ten minutes, brisk, phone away. Two hours of energy and more ideas than the desk.'),
        dict(kind='check',
             question="It's 3pm and you're flat. Which gives energy for the longest, with no crash?",
             choices=['A brisk ten-minute walk, ideally outside', 'A candy bar, then straight back to the desk', 'A second coffee and a cold glass of water'],
             answer=0,
             why='The walk gave two hours with no crash, the candy gave one hour then more tiredness, and a 3pm coffee is still half there at 8pm.'),
    ])
