LESSON = dict(
    id="hlth-4", track="health", minutes=3,
    title="The ten-minute walk",
    blurb="A short walk beats coffee for the afternoon and beats the desk for ideas. Here's the study that compared it to a candy bar, the creativity numbers, and how to fit it in.",
    takeaway="You learned what ten minutes of walking does to mood, energy, and ideas.",
    cards=[
        dict(kind="image", src="p01-slump", eyebrow="3pm",
             body="You are reading the same line for the fourth time. The options feel like coffee, a snack, or pushing through. There is a fourth one, and it has been tested against the snack.",
             paint="A college student at a library desk in the afternoon, cheek resting on one hand, eyes glazed over an open textbook, a vending-machine snack bar and a coffee cup beside the book, warm slanting light. Exactly one person. No words on the book, wrapper, or cup. The card says: reading the same line for the fourth time, and there is a fourth option."),
        dict(kind="image", src="fig-02-what-it-does", eyebrow="What it does",
             body="A brisk ten-minute walk raises your heart rate a little. More blood reaches the brain, and the chemicals that set mood shift. It is small. It is also fast, free, and measured."),
        dict(kind="image", src="fig-03-candy", eyebrow="Walk vs candy bar",
             body="In one study people got either a candy bar or a ten-minute walk. The candy gave energy for an hour, then more tiredness and tension. The walk gave energy for two hours, no crash."),
        dict(kind="image", src="fig-04-ideas", eyebrow="Ideas",
             body="Stanford tested people on inventing new uses for objects, sitting and then walking. Walking raised their creative output by about 60%. Four in five people did better on their feet."),
        dict(kind="image", src="p05-outside", eyebrow="Outside if you can",
             body="Outdoors adds a little more: light, which resets your clock, and a change of scene. But a lap of the building counts. The walk is the thing. The scenery is a bonus.",
             paint="A college student walking briskly along a tree-lined campus path in bright afternoon light, arms swinging, chin up, a light backpack, dappled shade on the ground, a building behind. Exactly one person. No signs or words. The card says: outdoors adds light and a change of scene, but a lap of the building counts."),
        dict(kind="image", src="fig-06-when", eyebrow="When it fits",
             body="Three natural slots. After lunch, when the dip hits. Before a hard task, for ideas. After studying, to let it settle. Pick one and tie it to something you already do."),
        dict(kind="image", src="p07-phone", eyebrow="Phone in your pocket",
             body="Leave the phone in your pocket or the walk is just scrolling upright. Let the mind wander. That wandering is where the creativity study got its effect.",
             paint="A college student walking along a river path, hands free, phone tucked in a back pocket, gazing off at the water with a loose, thinking expression, golden light, a bridge in the distance. Exactly one person. No signs or words. The card says: leave the phone in your pocket and let the mind wander."),
        dict(kind="image", src="fig-08-stack", eyebrow="Stack it",
             body="Ten minutes a day is 70 minutes a week and about two hours of extra energy each afternoon. Walk to the far coffee shop. Take the call standing up. It adds up without a gym."),
        dict(kind="image", src="p09-back", eyebrow="Back at the desk",
             body="Come back and read that line again. It reads the first time now. That is not willpower. That is blood flow. Do it again tomorrow.",
             paint="The same library desk: the college student back in the chair, cheeks a little flushed from the air, sitting upright and reading the textbook with a clear, alert face, the snack bar pushed aside unopened. Exactly one person. No words on anything. The card says: come back and the line reads the first time now."),
        dict(kind="key", body="Ten minutes, brisk, phone away. Two hours of energy and more ideas than the desk."),
        dict(kind="check",
             question="It's 3pm and you're flat. Which gives energy for the longest, with no crash?",
             choices=["A brisk ten-minute walk, ideally outside",
                      "A candy bar, then straight back to the desk",
                      "A second coffee and a cold glass of water"],
             answer=0,
             why="The walk gave two hours of energy and no crash. The candy gave one hour, then more tiredness. Caffeine this late is still half there at 8pm, so it costs tonight's sleep."),
    ])
