LESSON = dict(
    id='hlth-3', track='health', minutes=3,
    title='Anxiety is a body thing first',
    blurb="The racing heart comes before the worried thoughts, not after. You'll see why, the breathing pattern a 2023 Stanford study found beats meditation, and what to do with the thoughts once the body's quiet.",
    takeaway='Calm the body first, because the mind follows it.',
    cards=[
        dict(kind='image', src='p01-exam-hall', eyebrow='Before the exam',
             body="Heart going, hands cold, stomach tight. Then the thoughts arrive: 'I'm going to fail.' It feels like the thought caused the feeling, and usually it's the other way round, which changes what you do about it.",
             paint='A college student sitting at a desk in a big exam hall before the start, hands pressed flat on the desk, shoulders tight, staring straight ahead, rows of other students soft and out of focus behind them, cool morning light from tall windows. Exactly one person in focus, background figures soft. No words on any paper. The card says: heart going, hands cold, and then the thoughts arrive.'),
        dict(kind='image', src='fig-02-what-it-is', eyebrow='What it is',
             body="Anxiety is the body's alarm system running when there's no fire. The alarm is physical: fast heart, fast breath, tight muscles. The thoughts are the brain trying to explain the alarm, and it isn't a reliable narrator."),
        dict(kind='image', src='fig-03-loop', eyebrow='The loop',
             body="Body fires, brain explains, the explanation scares the body more, and round it goes. You can't argue with the thoughts while the body's at full alarm, so start with the body. The thoughts wait."),
        dict(kind='image', src='fig-04-sigh', eyebrow='The physiological sigh',
             body="Breathe in through the nose. At the top, take one more short sip of air. Then a long, slow breath out through the mouth. That's one, and you do it three times, which takes about a minute."),
        dict(kind='image', src='fig-05-why', eyebrow='Why the exhale',
             body='Your heart speeds up a little when you breathe in and slows when you breathe out. A long exhale tips the balance toward slow, and a minute of it turns the alarm down without you having to believe anything.'),
        dict(kind='image', src='fig-06-study', eyebrow='The study',
             body="In 2023, a Stanford team led by Melis Balban compared five minutes a day of this breathing with five minutes of meditation. The breathing group's mood improved more, and their resting breathing rate dropped. Five minutes, no app."),
        dict(kind='image', src='p07-walk', eyebrow='Move the alarm',
             body='The alarm wants you to run, so walk. Five minutes, fast, outside if you can. The body gets to do the thing it was gearing up for and stands down, which no amount of sitting still can manage.',
             paint='A college student walking fast along a campus path in cool morning air, hands out of pockets, breath visible, face set but easing, trees and a low sun behind. Exactly one person. No signs or words. The card says: the alarm wants you to run, so walk, five minutes, fast.'),
        dict(kind='image', src='fig-08-thoughts', eyebrow='Then the thoughts',
             body="Once the body's quieter, look at the thought. 'I'm going to fail' becomes 'I'm worried about question three.' Smaller, truer, and something you can act on tonight instead of dread all week."),
        dict(kind='image', src='p09-help', eyebrow="When it's every day",
             body="Nerves before an exam are normal. Alarm most days for weeks is different. Campus counselling is free at most schools and the wait is shorter than people think. It's a body thing, and it's worth getting looked at.",
             paint='A calm, plant-filled counselling office in daylight, a college student in an armchair talking with visible relief, a counsellor in their forties listening warmly with a notebook on their knee, a box of tissues on a side table. Exactly two people. No words on the notebook, posters, or door. The card says: alarm most days for weeks is different, and campus counselling is free.'),
        dict(kind='key', body='Body first. Double inhale, long exhale, three times. Then the thoughts get smaller.'),
        dict(kind='check',
             question="Heart racing before a presentation. What's the first move?",
             choices=['Three slow breaths: double inhale, long exhale, then think', "Tell yourself firmly that there's nothing to be scared of", 'Run through your notes one more time so you feel prepared'],
             answer=0,
             why="The alarm is physical, so words can't reach it yet, and the long exhale slows the heart in about a minute."),
    ])
