LESSON = dict(
    id='work-11', track='work', minutes=3,
    title='Ask for the reference before you need it',
    blurb="A reference is a person, and people forget. You'll see when to ask, the one word that gives them an out, the lead times a letter needs, and the one page that makes saying yes easy.",
    takeaway='Line up references while people still remember you, then keep them warm.',
    cards=[
        dict(kind='image', src='p01-last-day', eyebrow='The last day',
             body="It's the last day of your internship and your manager likes you. In six months they'll have forgotten your project's name. Ask now, while it's fresh, for something you won't need until much later.",
             paint="The last day of an internship: a college-age intern standing at a manager's desk to say goodbye, the manager in their forties standing to shake hands with real warmth, a small potted plant and a window with late-summer light. Exactly two people. No words on screens or walls. The card says: it is the last day, your manager likes you, ask now while it is fresh."),
        dict(kind='image', src='fig-02-what-it-is', eyebrow='What a reference is',
             body='A reference is a person a future employer calls to ask what you were like. A recommendation letter is the same thing written down, mostly for grad school. Both need someone who remembers you well, and memory is the whole problem.'),
        dict(kind='image', src='fig-03-when', eyebrow='When to ask',
             body='Ask at the end of the job, the course, or the project, not when you need it. A yes given now holds for years. A cold ask two years on gets a maybe, and a maybe on the phone sounds like a no.'),
        dict(kind='image', src='fig-04-sentence', eyebrow='The sentence',
             body="'Would you be comfortable being a strong reference for me?' The word 'comfortable' gives them an out. If they hesitate, thank them and ask someone else, because a lukewarm reference does more damage than none at all."),
        dict(kind='image', src='p05-office-hours', eyebrow='For professors',
             body="A professor with 200 students can't write about someone they've never spoken to. Go to office hours twice and ask one real question each time. Now you're a face, and a letter is possible. Skip that and there's nothing to write.",
             paint="A professor's small book-lined office: a college student in the visitor's chair asking a question with an open notebook, the professor, older, leaning back with a pleased, engaged expression, afternoon light through a narrow window. Exactly two people. Book spines are plain colours with no titles, no words anywhere. The card says: go to office hours twice, ask one real question each time."),
        dict(kind='image', src='fig-06-one-page', eyebrow='The one page',
             body="When you use them, send one page: the job, the deadline, what you did for them, two things you'd like them to mention. You aren't being pushy. You're making it easy, and easy is what gets done on time."),
        dict(kind='image', src='fig-07-lead-time', eyebrow='Lead time',
             body="A phone reference needs a week's warning. A letter needs three to four weeks, and a grad school letter needs six. Asking for a letter due Friday is asking for a no, or worse, a rushed one that says nothing."),
        dict(kind='image', src='p08-keep-warm', eyebrow='Keep them warm',
             body="Once a year, send two lines: what you're doing, and one thing you learned from them. No ask. Then when you do ask, you aren't a stranger from three years ago, you're someone they've been quietly rooting for.",
             paint='A college graduate in a new apartment at a small kitchen table, typing a short message on a laptop with a fond little smile, a photo frame and a plant on the table, morning light. Exactly one person. The screen shows only two short grey lines, no words. The card says: once a year, send two lines, no ask.'),
        dict(kind='image', src='p09-thanks', eyebrow='Close the loop',
             body="Whatever happens, tell them: 'I got it, thank you' or 'I didn't, but thank you.' People who hear the ending say yes next time. People who never hear back don't, and they remember that too.",
             paint='A professor at their desk reading something on a phone and breaking into a proud, delighted smile, one hand to their chest, a stack of plain-coloured books beside them, warm office light. Exactly one person. The phone shows only a soft page, no words. The card says: whatever happens, tell them the ending.'),
        dict(kind='key', body="Ask at the end, while they remember. 'Comfortable' gives them an out. Send one page."),
        dict(kind='check',
             question="Your internship ends Friday. You won't need a reference for a year. What do you do?",
             choices=['Ask on Friday, then send a two-line update once a year', 'Wait until you need it, so the ask is specific and real', 'Ask HR to keep a note on file that you did good work'],
             answer=0,
             why='Memory of you fades fastest in the first months, so a yes given now and kept warm stays strong while a cold ask in a year gets a vague one.'),
    ])
