LESSON = dict(
    id='ppl-10', track='people', minutes=3,
    title='A compliment that sticks is specific',
    blurb="'Great job' is forgotten by lunch. You'll see why specific praise sticks, what Carol Dweck's research says to praise so it helps, and the two places a compliment counts double.",
    takeaway='Name the thing, praise the choice, say what it did for you.',
    cards=[
        dict(kind='image', src='p01-great-job', eyebrow='Great job',
             body="Your friend nails a presentation and you say 'great job!' They say thanks, and by lunch neither of you remembers it. It was kind and it was also nothing, and there's a version of it they'd keep for years.",
             paint='A college seminar room just after a presentation: one student stepping away from the front with a relieved smile, a friend in the front row giving a quick thumbs up, three other students gathering bags in the background. Exactly five people. The screen behind shows only coloured shapes, no words. The card says: you say great job, they say thanks, and by lunch neither of you remembers it.'),
        dict(kind='image', src='fig-02-what-it-is', eyebrow='What a compliment is',
             body="A compliment is telling someone what they did well so they know to do it again. 'Great job' has no information in it, so it can't be repeated. Specific praise can, which is the whole difference."),
        dict(kind='image', src='fig-03-specific', eyebrow='Name the thing',
             body="'The way you paused before the numbers made everyone look up.' Now they know what worked. That sentence is worth fifty 'great jobs', because it proves you were paying attention and nobody can fake it."),
        dict(kind='image', src='fig-04-choice', eyebrow='The choice, not the talent',
             body="Praise what they chose, not what they are. Carol Dweck's studies found kids told 'you're so smart' picked easier tasks next time, while kids praised for effort picked harder ones, and adults don't behave much differently."),
        dict(kind='image', src='p05-effect', eyebrow='Say what it did for you',
             body="Add the effect: 'Your notes got me through that exam.' Now it isn't a rating, it's a thank-you with evidence. People remember what they did for you long after they've forgotten being rated.",
             paint='Two college students walking out of an exam hall into sunlight, one turning to the other with a grateful, animated face and a hand on their shoulder, the other looking surprised and pleased, a few students streaming out behind them. Exactly two people in focus, the background figures soft. No words on signs or papers. The card says: your notes got me through that exam.'),
        dict(kind='image', src='fig-06-two-places', eyebrow='Where it counts double',
             body='In front of others, and to their boss. Praise in a group costs you nothing and gives them status. A two-line email to their manager can change their year. Both are rare, which is exactly why both land.'),
        dict(kind='image', src='p07-receive', eyebrow='Receiving one',
             body="When you get a compliment, say 'thank you' and stop. Not 'oh, it was nothing'. Deflecting tells them their judgement was wrong. Take it, and give one back later, not in the same breath, or it reads as a trade.",
             paint='A college student receiving a compliment from an older coworker at a cafe counter, the student standing straight with a simple warm smile, hand lightly on their own chest, not waving it away, the coworker nodding. Exactly two people. No menu boards, no logos, no words. The card says: say thank you and stop, do not deflect it.'),
        dict(kind='image', src='fig-08-timing', eyebrow='Soon, not perfect',
             body="Say it within a day. A specific compliment a week late is still good, and a perfect one you never sent is worth nothing. A two-line text counts. The catch is it has to be true, or they'll know within a second."),
        dict(kind='image', src='p09-habit', eyebrow='One a day',
             body="Try one real compliment a day for a week: specific, about a choice, with the effect on you. Watch how people's faces change, and then watch how they start treating you. It's uncomfortable for about three days.",
             paint="A sunny campus quad in the morning, a college student saying something kind to a friend on a bench, the friend's face lighting up in genuine surprise, coffee cups in hand, trees and a path behind. Exactly two people. No words anywhere. The card says: one real compliment a day for a week, and watch faces change."),
        dict(kind='key', body='Name the thing, praise the choice, say what it did for you. Say it within a day.'),
        dict(kind='check',
             question='Your roommate cooked dinner for everyone. Which compliment will they remember?',
             choices=["'Timing the rice with the curry made it all land hot. Thank you.'", "'You're honestly such a natural cook, that was really amazing.'", "'Great dinner! We should honestly do this every single week.'"],
             answer=0,
             why='It names a choice they made and what it did for you, while the other two rate them and give them nothing to do again.'),
    ])
