LESSON = dict(
    id="ppl-10", track="people", minutes=3,
    title="A compliment that sticks is specific",
    blurb="'Great job' is forgotten by lunch. Here's why specific praise lands, what to praise so it helps, and the two places a compliment does the most.",
    takeaway="You learned to give praise that is specific, about a choice, and useful.",
    cards=[
        dict(kind="image", src="p01-great-job", eyebrow="Great job",
             body="Your friend nails a presentation. You say 'great job!' They say thanks. By lunch neither of you remembers it. It was kind. It was also nothing. Here is the version they keep.",
             paint="A college seminar room just after a presentation: one student stepping away from the front with a relieved smile, a friend in the front row giving a quick thumbs up, three other students gathering bags in the background. Exactly five people. The screen behind shows only coloured shapes, no words. The card says: you say great job, they say thanks, and by lunch neither of you remembers it."),
        dict(kind="image", src="fig-02-what-it-is", eyebrow="What a compliment is",
             body="A compliment is telling someone what they did well, so they know to do it again. 'Great job' has no information in it. It cannot be repeated. Specific praise can."),
        dict(kind="image", src="fig-03-specific", eyebrow="Name the thing",
             body="'The way you paused before the numbers made everyone look up.' Now they know what worked. That sentence is worth fifty 'great jobs'. It proves you were paying attention."),
        dict(kind="image", src="fig-04-choice", eyebrow="The choice, not the talent",
             body="Praise what they chose, not what they are. 'You're so smart' makes people afraid to look dumb next time. 'You practised that until it was easy' makes them want to practise again."),
        dict(kind="image", src="p05-effect", eyebrow="Say what it did for you",
             body="Add the effect. 'Your notes got me through that exam.' Now it is not a rating. It is a thank-you with evidence. People remember what they did for you long after they forget being rated.",
             paint="Two college students walking out of an exam hall into sunlight, one turning to the other with a grateful, animated face and a hand on their shoulder, the other looking surprised and pleased, a few students streaming out behind them. Exactly two people in focus, the background figures soft. No words on signs or papers. The card says: your notes got me through that exam."),
        dict(kind="image", src="fig-06-two-places", eyebrow="Where it counts double",
             body="In front of others, and to their boss. Praise in a group costs you nothing and gives them status. A two-line email to their manager can change their year. Both are rare, so both land."),
        dict(kind="image", src="p07-receive", eyebrow="Receiving one",
             body="When you get a compliment, say 'thank you' and stop. Not 'oh, it was nothing'. Deflecting tells them their judgement was wrong. Take it, and give one back later, not in the same breath.",
             paint="A college student receiving a compliment from an older coworker at a cafe counter, the student standing straight with a simple warm smile, hand lightly on their own chest, not waving it away, the coworker nodding. Exactly two people. No menu boards, no logos, no words. The card says: say thank you and stop, do not deflect it."),
        dict(kind="image", src="fig-08-timing", eyebrow="Soon, not perfect",
             body="Say it within a day. A specific compliment a week late is still good. A perfect one you never sent is worth nothing. A text works. Two lines work."),
        dict(kind="image", src="p09-habit", eyebrow="One a day",
             body="Try one real compliment a day for a week. Specific, about a choice, with the effect on you. Watch how people's faces change. Then watch how they start treating you.",
             paint="A sunny campus quad in the morning, a college student saying something kind to a friend on a bench, the friend's face lighting up in genuine surprise, coffee cups in hand, trees and a path behind. Exactly two people. No words anywhere. The card says: one real compliment a day for a week, and watch faces change."),
        dict(kind="key", body="Name the thing, praise the choice, say what it did for you. Say it within a day."),
        dict(kind="check",
             question="Your roommate cooked dinner for everyone. Which compliment will they remember?",
             choices=["'Timing the rice with the curry made it all land hot. Thank you.'",
                      "'You're honestly such a natural cook, that was really amazing.'",
                      "'Great dinner! We should honestly do this every single week.'"],
             answer=0,
             why="It names a choice they made and what it did for you. The other two rate them, which is nice but gives them nothing to do again."),
    ])
