LESSON = dict(
    id="hlth-8", track="health", minutes=3,
    title="What 'drink more water' really means",
    blurb="Eight glasses a day was never a rule. Here's where the number came from, what thirst and pee colour tell you, and what mild dehydration does to focus.",
    takeaway="You learned how much water is actually enough, and how to check.",
    cards=[
        dict(kind="image", src="p01-jug", eyebrow="The gallon jug",
             body="Someone in your class carries a gallon jug. Someone else lives on coffee and swears they are fine. Both have heard 'eight glasses a day'. Neither knows where it came from. Nobody does.",
             paint="A college lecture hall row: one student with an enormous clear plastic water jug on the desk, sipping proudly, and beside them another student cradling a paper coffee cup with a sceptical sideways glance, two other students soft in the background. Exactly two people in focus, background soft. No words or logos on the jug or cup. The card says: one carries a gallon jug, one lives on coffee, and neither knows where eight glasses came from."),
        dict(kind="image", src="fig-02-eight", eyebrow="Where eight came from",
             body="The eight-glasses rule has no study behind it. Researchers went looking in 2002 and found nothing. The number that does exist is a daily total, and it includes food and coffee."),
        dict(kind="image", src="fig-03-real-number", eyebrow="The real number",
             body="The guideline is about 2.7 litres a day for women and 3.7 for men, from everything. Around a fifth comes from food. That leaves roughly 9 cups of drinks for women, 12 for men. All drinks count."),
        dict(kind="image", src="fig-04-counts", eyebrow="Coffee counts",
             body="Coffee and tea count. Caffeine makes you pee a little more, but you keep most of the water in the cup. A latte is mostly water. So is soup. So is fruit."),
        dict(kind="image", src="p05-thirst", eyebrow="Thirst works",
             body="If you are young and healthy, thirst is a good gauge. Drink when thirsty, a bit extra in heat or after a run. You do not need an app. You need to notice.",
             paint="A college student in running clothes, flushed and sweaty, drinking from a campus water fountain in bright sunlight, one hand on the fountain, eyes closed in relief, a path and trees behind. Exactly one person. No logos or words on clothes or fountain. The card says: thirst is a good gauge, drink when thirsty and extra after a run."),
        dict(kind="image", src="fig-06-colour", eyebrow="The colour check",
             body="Pale straw is right. Clear means you can ease off. Dark yellow means drink now. The check is free, takes two seconds, and beats any tracker."),
        dict(kind="image", src="fig-07-focus", eyebrow="What a little dry does",
             body="Losing just 1 to 2% of your body's water dents mood and focus and can bring on a headache. That happens before you feel very thirsty. That is one long lecture without a bottle."),
        dict(kind="image", src="p08-bottle", eyebrow="The lazy fix",
             body="Keep a bottle where you sit. Not a jug, a bottle. Sip when you notice it. The point is not a target. The point is that the water is closer than the vending machine.",
             paint="A tidy study desk by a window, a college student writing in a notebook, a plain reusable water bottle within easy reach beside the laptop, afternoon light, a plant. Exactly one person. No words or logos on the bottle, screen, or notebook. The card says: keep a bottle where you sit and sip when you notice it."),
        dict(kind="image", src="p09-hot-day", eyebrow="When it matters more",
             body="Hot days, hangovers, a fever, a long run. Those are when 'drink more' is real advice. Add a glass an hour, and salt if you are sweating a lot. The rest of the time, thirst has it.",
             paint="A blazing hot summer day on a campus lawn, two college students in the shade of a tree passing a large water bottle between them, one wiping their forehead, a frisbee on the grass, heat haze in the distance. Exactly two people. No words or logos anywhere. The card says: hot days, hangovers, fever, and long runs are when drink more is real advice."),
        dict(kind="key", body="Eight glasses was never a rule. Thirst and pale-straw pee are the gauge. All drinks count."),
        dict(kind="check",
             question="You drink two coffees and a tea a day and rarely feel thirsty. Your pee is pale. Dehydrated?",
             choices=["No. Thirst and pale pee say you're fine, and the drinks count",
                      "Yes. Caffeine cancels out the water in coffee and tea, mostly",
                      "Probably. Anyone under eight glasses of plain water is short"],
             answer=0,
             why="The colour check and thirst are the real gauges. Coffee and tea keep most of their water. The eight-glasses rule has no study behind it."),
    ])
